---
- name: Check log compression
  shell: grep -rE '(^|[^#y])compress' /etc/logrotate.d
  register: log_compression
  changed_when: False
  failed_when: log_compression.rc > 1
  check_mode: no

- name: Disable log compression (zfs already compresses them)
  shell: |
    for file in /etc/logrotate.d/* ; do
        if grep -Eq "(^|[^#y])compress" "$file" ; then
            sed -i -r "s/(^|[^#y])(compress)/\1#\2/" "$file"
        fi
    done
  when: log_compression.rc == 0

