---
- name: Add self to monitoring
  copy:
    dest: "/srv/prometheus/{{ 'secure_' if self_monitoring_use_https else '' }}targets/{{ self_monitoring_target_host }}_{{ self_monitoring_target_port }}.yml"
    content: |
      - targets:
        - {{ self_monitoring_target_host }}:{{ self_monitoring_target_port }}
  delegate_to: "{{ self_monitoring_monitor_host }}"
  remote_user: "{{ self_monitoring_remote_user }}"
  become: "{{ self_monitoring_remote_become }}"
  tags: self_monitoring