---
- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Start apt exporter
  service:
    name: prometheus-node-exporter-apt.service
    state: started

- name: Start smartmon exporter
  service:
    name: prometheus-node-exporter-smartmon.service
    state: started
