---
- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Start apt exporter
  systemd:
    name: prometheus-node-exporter-apt.service
    daemon-reload: yes
    enabled: yes
    state: started

- name: Start smartmon exporter
  systemd:
    name: prometheus-node-exporter-smartmon.timer
    daemon-reload: yes
    enabled: yes
    state: started

- name: Start apt timer
  systemd:
    name: prometheus-node-exporter-apt.timer
    daemon-reload: yes
    enabled: yes
    state: started

- name: Restart node exporter
  systemd:
    name: prometheus-node-exporter
    daemon-reload: yes
    enabled: yes
    state: restarted
