---
- hosts: all
  remote_user: pi
  gather_facts: yes
  become: yes

  handlers:
    - include: ../../handlers/handlers.yml
    - name: Restart dhcpcd
      service: name=dhcpcd state=restarted

  vars:
    - hostname: borderreouter.chacal.fi
    - apt_upgrade: false
    - timezone: Europe/Helsinki
    - lan_network: 10.60.0.0/24
    - router_ip_address: 10.60.0.1
    - router_ipv6_address: fddd:eeee:ffff:60::1
    - lan_ip_address: 10.60.0.2
    - lan_ipv6_address: fddd:eeee:ffff:60::2
    - wpan_ipv6_address: fddd:eeee:ffff:61::1

  vars_files:
    - secrets.yml

  roles:
    - common
    - role: wificlient
      wificlient_interface: wlan0
      wificlient_networks:
       - ssid: "{{ chacal.known_wlans.iot.ssid }}"
         psk: "{{ chacal.known_wlans.iot.psk }}"
    - role: sendgrid_with_dma
      sendgrid_api_key: "{{ chacal.sendgrid.buster_base }}"
    - role: debian_common
      unattended_upgrades_origins: '"o=Docker";'
    - role: docker-app
      docker_app_name: "wpantund"
      docker_app_container_name: "jihartik/wpantund-armv6"
      docker_app_extra_params: "--network host --cap-add=NET_ADMIN --device=/dev/ttyACM0"
      docker_app_env:
        - OPENTHREAD_DEVICE_PORT=/dev/ttyACM0
      tags: wpantund

  tasks:
    - name: Enable IPv6 forwarding
      lineinfile: dest=/etc/sysctl.conf regexp='.*net.ipv6.conf.all.forwarding.*' line='net.ipv6.conf.all.forwarding=1'
      notify: reload_sysctl

    - name: Remove dhcpcd
      apt:
        state: absent
        cache_valid_time: 3600
        pkg:
          - dhcpcd5

    - name: Setup networking
      copy:
        dest: /etc/network/interfaces
        content: |
          source-directory /etc/network/interfaces.d

          auto lo
          iface lo inet loopback
              dns-nameservers {{ router_ip_address }} 1.1.1.1 8.8.8.8
              dns-search chacal.fi

          auto eth0
          iface eth0 inet dhcp

          auto wlan0
          allow-hotplug wlan0
          iface wlan0 inet static
            address {{ lan_ip_address }}/24
            gateway {{ router_ip_address }}
            wpa-conf /etc/wpa_supplicant/wpa_supplicant-wlan0.conf
          iface wlan0 inet6 static
            address {{ lan_ipv6_address }}/64
            gateway {{ router_ipv6_address }}

          auto wpan0
          allow-hotplug wpan0
          iface wpan0 inet6 static
            address {{ wpan_ipv6_address }}/64
      notify: restart-networking
      tags: networking
