---
- hosts: all
  remote_user: jihartik
  gather_facts: yes
  become: yes

  handlers:
    - include: ../../handlers/handlers.yml

  vars_files:
    - secrets.yml

  roles:

  tasks:
    - name: Add default user to sudo group
      lineinfile:
        name: /etc/sudoers
        state: present
        regexp: '^{{ ansible_ssh_user }}\s'
        line: '{{ ansible_ssh_user }} ALL=(ALL) NOPASSWD: ALL'

    - name: Install/update dependencies
      apt: pkg={{ item }} state=latest
      with_items:
        - python-pip
        - python3-dev
        - python-setuptools
        - mosquitto
        - mosquitto-clients

    - name: Install virtualenv
      pip: name=virtualenv state=latest

    - name: Add user for Home Assistant
      user: name=homeassistant system=yes

    - name: Create HA installation directory
      file: path=/srv/homeassistant state=directory mode=0755 owner=homeassistant

    - name: Install Home Assistant
      pip: name=homeassistant state=latest virtualenv=/srv/homeassistant virtualenv_python=python3
      become: true
      become_user: homeassistant

    - name: Copy systemd unit file
      copy:
        dest: /etc/systemd/system/home-assistant.service
        content: |
          [Unit]
          Description=Home Assistant
          After=network.target

          [Service]
          Type=simple
          User=homeassistant
          #make sure the virtualenv python binary is used
          Environment=VIRTUAL_ENV="/srv/homeassistant"
          Environment=PATH="$VIRTUAL_ENV/bin:$PATH"
          ExecStart=/srv/homeassistant/bin/hass -c "/home/homeassistant/.homeassistant"
          Restart=always

          [Install]
          WantedBy=multi-user.target
      register: unit_file

    - name: Create HA configuration directory
      file: path=/home/homeassistant/.homeassistant state=directory mode=0755 owner=homeassistant

    - name: Copy configuration file
      copy: dest=/home/homeassistant/.homeassistant/configuration.yaml src=./conf/ha-configuration.yaml owner=homeassistant
      register: conf_file

    - name: Copy devicesfile
      copy: dest=/home/homeassistant/.homeassistant/known_devices.yaml.yaml src=./conf/ha-known_devices.yaml owner=homeassistant
      register: devices_file

    - name: Enable service and start it
      systemd: name=home-assistant daemon_reload=yes state=restarted enabled=yes
      when: (unit_file is defined and unit_file.changed) or (conf_file is defined and conf_file.changed) or (devices_file is defined and devices_file.changed)

    - name: Mosquitto config file
      copy:
        dest: /etc/mosquitto/conf.d/custom.conf
        content: |
          listener 1883

          listener 8883
          protocol websockets
      register: mosquitto_conf_file

    - name: Create own Mosquitto unit file
      copy:
        dest: /etc/systemd/system/mosquitto.service
        content: |
          [Unit]
          Description=Mosquitto MQTT broker

          [Service]
          User=mosquitto
          Group=mosquitto
          Type=simple
          ExecStart=/usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
          Restart=always
          RestartSec=5

          [Install]
          WantedBy=multi-user.target
      register: mosquitto_unit_file

    - name: Enable mosquitto and start it
      systemd: name=mosquitto daemon_reload=yes state=restarted enabled=yes
      when: (mosquitto_unit_file is defined and mosquitto_unit_file.changed) or (mosquitto_conf_file is defined and mosquitto_conf_file.changed)
