---
- hosts: all
  remote_user: pi
  gather_facts: yes
  become: yes

  handlers:
    - include: ../../handlers/handlers.yml

  vars:
    - hostname: haukkakallio-gw
    - apt_upgrade: false
    - timezone: Europe/Helsinki
    - aws_access_key_id: "{{ chacal.aws.haukkakalliogw.access_key }}"
    - aws_secret_access_key: "{{ chacal.aws.haukkakalliogw.secret_key }}"

  vars_files:
    - secrets.yml

  roles:
    - common
    - role: unattended_upgrades
    - role: huawei_e3372h
    - role: upnpc
      upnpc_interface: eth1
      upnpc_port_forwards: "500 UDP 4500 UDP 1701 UDP"
    - role: nat_router
      nat_router_local_interface: eth0
      nat_router_inet_interface: eth1
      nat_router_ip: 10.90.90.1
      nat_router_dhcp_range: "10.90.90.50,10.90.90.150,24h"
      nat_router_static_ips: "{{ chacal.nat_router_static_ips }}"
    - role: l2tp_vpn_server
      l2tp_vpn_psk: "{{ chacal.l2tp_vpn_psk }}"
      l2tp_vpn_local_ip: 10.90.90.1
      l2tp_vpn_local_ip_range: 10.90.90.200-10.90.90.250
    - role: route53-ddns
      route53_zoneid: "{{ chacal.route53.haukkakallio.zoneid }}"
      route53_cname: "{{ chacal.route53.haukkakallio.cname }}"
