---
#
# Playbook that sets up PostgreSQL and Home Assistant on homeassistant.dmz.chacal.fi
#
- hosts: homeassistant.dmz.chacal.fi
  remote_user: jihartik
  become: true

  vars_files:
    - secrets.yml

  vars:
    docker_custom_registry: "https://docker-registry.chacal.fi"
    ha_environment_sensors:
      - tag: S201
        name: Kids room
      - tag: S202
        name: Study
      - tag: S203
        name: Master bedroom
      - tag: S204
        name: Bathroom
      - tag: S206
        name: Livingroom
      - tag: S208
        name: Storage
      - tag: S209
        name: Guestroom
      - tag: S210
        name: Ventilation, outside air
      - tag: S211
        name: Ventilation, pre-heated air
      - tag: S212
        name: WC, downstairs
      - tag: S213
        name: Outside, balcony
      - tag: S214
        name: Sauna
      - tag: S215
        name: Car
      - tag: S222
        name: Outside, backyard
    ha_motion_sensors:
      - tag: P301
        name: Storage
      - tag: P302
        name: WC, downstairs
      - tag: P303
        name: WC, downstairs
      - tag: P304
        name: WC, downstairs
      - tag: P306
        name: WC, downstairs
      - tag: P307
        name: WC, upstairs
      - tag: P308
        name: WC, upstairs
      - tag: P309
        name: Storage

  handlers:
    - name: Restart Home Assistant
      service: name=home-assistant state=restarted

  roles:
    - role: filebeat
      filebeat_elasticsearch_hosts:
        - elastic.chacal.fi
    - role: debian_common
      unattended_upgrades_origins: '"o=elastic";"o=Docker";'
    - role: prometheus_node_exporter
    - role: self_monitoring
    - role: ouroboros
      ouroboros_notifier: "sendgrid://{{ chacal.sendgrid.ouroboros }}:root@{{ inventory_hostname }}/{{ chacal.ouroboros.email }}"
    - role: duplicacy
      duplicacy_filters: |
        +srv/
        +srv/postgres/*
        +srv/home-assistant/*
        -*
      duplicacy_backup_hours: "1,13"
      duplicacy_prune_hours: "1,13"
      duplicacy_prune_minutes: "45"
      duplicacy_encryption_key: "{{ chacal.ha.duplicacy.encryption_key }}"
      duplicacy_environment:
        DUPLICACY_B2_ID: "{{ chacal.ha.duplicacy.b2_id }}"
        DUPLICACY_B2_KEY: "{{ chacal.ha.duplicacy.b2_key }}"

  tasks:
    #
    #  Install PostgreSQL
    #
    - name: Create PostgreSQL data directory
      file: path=/srv/postgres state=directory

    - name: Install PostgreSQL
      include_role:
        name: docker-app
      vars:
        docker_regular_user: "{{ ansible_user }}"
        docker_app_name: "postgres"
        docker_app_container_name: "postgres:12"
        docker_app_extra_params: "-v /srv/postgres:/var/lib/postgresql/data"
        docker_app_ports:
          - "127.0.0.1:5432:5432"
        docker_app_env:
          - "POSTGRES_USER=ha"
          - "POSTGRES_DB=ha"
          - "POSTGRES_PASSWORD={{ chacal.ha.postgres.password }}"



    #
    #  Install Home Assistant
    #
    - name: Create Home Assistant data directory
      file: path=/srv/home-assistant state=directory
      tags: home-assistant

    - name: Provision HA secrets
      template: src=./conf/homeassistant.dmz.chacal.fi/secrets.yaml.j2 dest=/srv/home-assistant/secrets.yaml mode=0600
      notify: Restart Home Assistant
      tags: home-assistant

    - name: Copy Home Assistant configuration file
      template:
        src: ./conf/homeassistant.dmz.chacal.fi/ha-configuration.yaml
        dest: /srv/home-assistant/configuration.yaml
        variable_start_string: '[['
        variable_end_string: ']]'
      notify: Restart Home Assistant
      tags: home-assistant

    - name: Copy Home Assistant automations file
      copy: src=./conf/homeassistant.dmz.chacal.fi/ha-automations.yaml dest=/srv/home-assistant/automations.yaml
      notify: Restart Home Assistant
      tags: home-assistant

    - name: Copy Home Assistant scenes file
      copy: src=./conf/homeassistant.dmz.chacal.fi/ha-scenes.yaml dest=/srv/home-assistant/scenes.yaml
      notify: Restart Home Assistant
      tags: home-assistant

    - name: Copy Home Assistant Kiosk dashboard file
      template:
        src: ./conf/homeassistant.dmz.chacal.fi/ha-dashboard-kiosk2.yaml
        dest: /srv/home-assistant/dashboard-kiosk2.yaml
        variable_start_string: '[['
        variable_end_string: ']]'
      notify: Restart Home Assistant
      tags: home-assistant

    - name: Create empty group and script configs
      file: path=/srv/home-assistant/{{ item }} state=touch
      loop:
        - groups.yaml
        - scripts.yaml
      changed_when: False
      tags: home-assistant

    - name: Create Home Assistant custom_components directory
      file: path=/srv/home-assistant/custom_components state=directory
      tags: home-assistant

    - name: Install Mount Kelvin integration
      git:
        repo: https://github.com/chacal/ha_mount_kelvin_integration.git
        dest: /srv/home-assistant/custom_components/mount_kelvin
        force: yes
        version: master
      register: mount_kelvin_git_pull
      tags: home-assistant

    - name: Install Home Assistant
      include_role:
        name: docker-app
      vars:
        docker_regular_user: "{{ ansible_user }}"
        docker_app_name: "home-assistant"
        docker_app_container_name: "homeassistant/home-assistant:stable"
        docker_app_extra_params: "--net=host -v /srv/home-assistant:/config --init"
        docker_app_env:
          - TZ=Europe/Helsinki
      tags: home-assistant

    - name: Restart Home Assistant
      service: name=home-assistant state=restarted enabled=yes
      when: mount_kelvin_git_pull.changed
      tags: home-assistant
