---
#
# This playbook is used to provision Mini after fresh Proxmox installation
# Assumptions:
#  - Passwordless SSH connection with "root"
#

- hosts: mini.chacal.fi
  remote_user: root

  vars_files:
    - secrets.yml

  vars:

  handlers:
    - name: Update boot parameters
      command: pve-efiboot-tool refresh

  roles:
    - role: pve_common
    - role: ikifi_with_dma
      tags: ikifi
    - role: debian_common
      unattended_upgrades_origins: '"o=Proxmox";"o=elastic";'
    - role: filebeat_remove

  tasks:
    - name: Install prometheus self reporting for node exporter
      include_role:
        name: self_monitoring
      tags: self_monitoring

    - name: Install prometheus self reporting for zfs exporter
      include_role:
        name: self_monitoring
      vars:
        self_monitoring_target_port: 9134  # ZFS exporter listens on port 9134
      tags: self_monitoring

    - name: Install prometheus self reporting for muuri.chacal.fi (pfSense) node exporter
      include_role:
        name: self_monitoring
      vars:
        self_monitoring_target_host: muuri.chacal.fi
      tags: self_monitoring

    - name: Enable IOMMU & serial console
      copy:
        dest: /etc/kernel/cmdline
        content: root=ZFS=rpool/ROOT/pve-1 boot=zfs intel_iommu=on
      notify: Update boot parameters

    - name: Add PVE admin user
      include_role:
        name: pve_admin_user
      vars:
        pve_admin_username: pve_admin
        pve_admin_pw_hash: "{{ chacal.mini.proxmox_user_pw_hash }}"
      tags: pve_admin_user

    - name: Setup networks
      copy:
        dest: /etc/network/interfaces
        content: |
          # network interface settings; autogenerated
          # Please do NOT modify this file directly, unless you know what
          # you're doing.
          #
          # If you want to manage parts of the network configuration manually,
          # please utilize the 'source' or 'source-directory' directives to do
          # so.
          # PVE will preserve these directives, but will NOT read its network
          # configuration from sourced files, so do not attempt to move any of
          # the PVE managed interfaces into external files!
          auto lo
          iface lo inet loopback

          auto vmbr0
          iface vmbr0 inet manual
              bridge-ports enp2s0
              bridge-stp off
              bridge-fd 0
          # eth0, WAN
          
          auto vmbr1
          iface vmbr1 inet manual
              bridge-ports enp3s0
              bridge-stp off
              bridge-fd 0
          # eth1, LAN
          
          auto vmbr2
          iface vmbr2 inet manual
              bridge-ports enp4s0
              bridge-stp off
              bridge-fd 0
          # eth2, OPT1
          
          auto enp5s0         
          iface enp5s0 inet static
              address 10.50.99.7/24
              gateway 10.50.99.1
              dns-nameservers 10.50.99.1
          # eth3, MGMT
      tags: networking

    - name: Setup Sanoid
      include_role: name=sanoid
      vars:
        sanoid_clean_empty_snapshots: True
        sanoid_clean_empty_snapshots_cron_hours: "*/6"
        sanoid_config: |
          [rpool]
                  use_template = pve_system
                  recursive = yes

          [rpool/data]
                  use_template = vm_disks
                  recursive = yes

          [template_pve_system]
                  frequent_period = 30
                  frequently = 0
                  hourly = 48
                  daily = 21
                  monthly = 3
                  yearly = 0
                  autosnap = yes
                  autoprune = yes

          [template_vm_disks]
                  frequent_period = 30
                  frequently = 0
                  hourly = 48
                  daily = 21
                  monthly = 12
                  yearly = 0
                  autosnap = yes
                  autoprune = yes
      tags: sanoid
