---
#
# Playbook that sets up MinIO server on minio.chacal.fi
#
- hosts: minio.chacal.fi
  remote_user: jihartik
  become: true

  vars_files:
    - secrets.yml

  vars:
    - aws_cli_user: root
    - aws_access_key_id: "{{ chacal.aws.home_infra_certbot.access_key }}"
    - aws_secret_access_key: "{{ chacal.aws.home_infra_certbot.secret_key }}"
    - docker_custom_registry: "https://docker-registry.chacal.fi"

  roles:
    - role: filebeat
      filebeat_elasticsearch_hosts:
        - elastic.chacal.fi
    - role: debian_common
      unattended_upgrades_origins: '"o=elastic";"o=Docker";'
    - role: prometheus_node_exporter
    - role: self_monitoring
    - role: ouroboros
      ouroboros_notifier: "sendgrid://{{ chacal.sendgrid.ouroboros }}:root@{{ inventory_hostname }}/{{ chacal.ouroboros.email }}"

  tasks:
    - name: Creat minio user
      user: name=minio system=yes
      tags: minio

    - name: Get minio uid & gid
      getent:
        database: passwd
        key: minio
      tags: minio

    - name: Create MinIO data directory
      file:
        path: /srv/minio
        state: directory
        owner: minio
        group: minio
        mode: 0750
      tags: minio

    - name: Setup Letsencrypt certificates
      include_role:
        name: certbot-dns-route53
      vars:
        certbot_email: "{{ chacal.certbot.email }}"
        certbot_deploy_hook: |
          #!/bin/bash
          echo "Restarting MinIO due to updated certificates.."
          mkdir -p /home/minio/certs
          cp /etc/letsencrypt/live/minio.chacal.fi/fullchain.pem /home/minio/certs/public.crt
          cp /etc/letsencrypt/live/minio.chacal.fi/privkey.pem /home/minio/certs/private.key
          chown -R minio:minio /home/minio/certs
          systemctl restart minio || true
      tags: certbot

    - name: Add MinIO docker service
      include_role:
        name: docker-app
      vars:
        docker_regular_user: "{{ ansible_user }}"
        docker_app_name: "minio"
        docker_app_container_name: "minio/minio"
        docker_app_extra_params: "-v /srv/minio:/data -v /home/minio/certs:/.minio/certs --user {{ getent_passwd.minio[1] }}:{{ getent_passwd.minio[2] }}"
        docker_app_container_params: "server /data"
        docker_app_ports:
          - 9000:9000
        docker_app_env:
          - "MINIO_ACCESS_KEY={{ chacal.minio.admin.access_key }}"
          - "MINIO_SECRET_KEY={{ chacal.minio.admin.secret_key }}"
      tags: minio
