#
# 1. Flash Raspbian using Raspberry Pi Imager
# 2. Enable SSH using public key
# 3. Set username to pi
# 4. Configure liilaa WLAN
# 5. Set locale
#
# 6. Boot Raspi & setup Static DHCP address on muuri: 10.50.1.12
# 7. Provision using this playbook
# 8. Add following lines to <Location /admin> in cupsd.conf
#      Allow @LOCAL
#      Allow 10.50.99.*
#      Allow 10.10.0.*
---
- hosts: printer.chacal.fi
  remote_user: pi
  become: yes

  handlers:
    - include: ../../handlers/handlers.yml
    - name: Restart cups
      service: name=cups state=restarted

  vars:
    - hostname: printer.chacal.fi
    - timezone: Europe/Helsinki

  vars_files:
    - secrets.yml

  roles:
    - common
    - role: prometheus_node_exporter
    - role: self_monitoring
    - role: ikifi_with_dma
      tags: ikifi
    - role: debian_common
      unattended_upgrades_origins: '"o=Raspbian"; "o=Raspberry Pi Foundation";'

  tasks:
    - name: Setup cups
      apt:
        pkg:
          - cups
          - printer-driver-splix
        state: latest
      tags: cups

    - name: Add regular user to lpadmin group
      user:
        name: "pi"
        groups: lpadmin
        append: yes
      tags: cups

    - name: Check cups status
      command: cupsctl
      register: cupsctl
      changed_when: False
      check_mode: no
      tags: cups

    - name: Allow printer sharing to network
      command: cupsctl --share-printers
      when: "'share_printers=1' not in cupsctl.stdout"
      tags: cups

    - name: Allow printing from MGMT network
      lineinfile:
        dest: /etc/cups/cupsd.conf
        state: present
        regexp: '^  Allow 10.50.99'
        insertafter: '^  Allow @LOCAL'
        line: '  Allow 10.50.99.*'
      notify: Restart cups
      tags: cups

    - name: Allow printing from WG network
      lineinfile:
        dest: /etc/cups/cupsd.conf
        state: present
        regexp: '^  Allow 10.10.0'
        insertafter: '^  Allow 10.50.99.*'
        line: '  Allow 10.10.0.*'
      notify: Restart cups
      tags: cups