---
- hosts: all
  remote_user: pi
  gather_facts: yes
  become: yes

  handlers:
    - include: ../../handlers/handlers.yml
    - name: Restart cups
      service: name=cups state=restarted

  vars:
    - hostname: printer.chacal.fi
    - apt_upgrade: false
    - timezone: Europe/Helsinki
    - lan_network: 10.90.70.0/24
    - router_ip_address: 10.90.70.1
    - lan_ip_address: 10.90.70.3

  vars_files:
    - secrets.yml

  roles:
    - common
    - role: prometheus_node_exporter
    - role: self_monitoring
    - role: wificlient
      wificlient_interface: wlan0
      wificlient_networks:
       - ssid: "{{ chacal.known_wlans.home.ssid }}"
         psk: "{{ chacal.known_wlans.home.psk }}"
    - role: sendgrid_with_dma
      sendgrid_api_key: "{{ chacal.sendgrid.buster_base }}"
    - role: debian_common
      unattended_upgrades_origins: '"o=Raspbian"; "o=Raspberry Pi Foundation";'

  tasks:
    - name: Remove dhcpcd
      apt:
        state: absent
        cache_valid_time: 3600
        pkg:
          - dhcpcd5

    - name: Setup networking
      copy:
        dest: /etc/network/interfaces
        content: |
          source-directory /etc/network/interfaces.d

          auto lo
          iface lo inet loopback
              dns-nameservers {{ router_ip_address }} 1.1.1.1 8.8.8.8
              dns-search chacal.fi

          auto eth0
          iface eth0 inet dhcp

          auto wlan0
          allow-hotplug wlan0
          iface wlan0 inet static
            address {{ lan_ip_address }}/24
            gateway {{ router_ip_address }}
            wpa-conf /etc/wpa_supplicant/wpa_supplicant-wlan0.conf

      notify: restart-networking
      tags: networking

    - name: Add regular user to lpadmin group
      user:
        name: "pi"
        groups: lpadmin
        append: yes
      tags: cups

    - name: Setup cups
      apt:
        pkg:
          - cups
          - printer-driver-splix
        state: latest
      tags: cups

    - name: Check cups status
      command: cupsctl
      register: cupsctl
      changed_when: False
      check_mode: no
      tags: cups

    - name: Allow printer sharing to network
      command: cupsctl --share-printers
      when: "'share_printers=1' not in cupsctl.stdout"
      tags: cups

    - name: Allow printing from MGMT network
      lineinfile:
        dest: /etc/cups/cupsd.conf
        state: present
        regexp: '^  Allow 10.90.99'
        insertafter: '^  Allow @LOCAL'
        line: '  Allow 10.90.99.*'
      notify: Restart cups
      tags: cups