---
#
# Playbook that sets up Buster base image after it has been built with Packer using preseed.cfg
#
- hosts: all
  become: true

  vars_files:
    - secrets.yml

  roles:
    - base_packages
    - role: unattended_upgrades
      unattended_upgrades_email: "{{ chacal.unattended_upgrades.to_email }}"
      unattended_upgrades_origins: '"n=${distro_codename}"; "n=${distro_codename}-updates";'
    - role: sendgrid_with_dma
      sendgrid_api_key: "{{ chacal.sendgrid.buster_base }}"
    - role: dotfiles
      github_token: "{{ chacal.github.access_tokens.https_cloning }}"

  tasks:
    - name: Remove installer logs
      file:
        path: /var/log/installer
        state: absent

