---
- hosts: all
  remote_user: pi
  gather_facts: yes
  become: yes

  handlers:
    - include: ../../handlers/handlers.yml

  vars:
    - hostname: raspigw
    - apt_upgrade: false

  vars_files:
    - secrets.yml

  roles:
    - common
    - role: huawei_e3372h
    - role: upnpc
      upnpc_interface: eth1
      upnpc_port_forwards: "500 UDP 4500 UDP 1701 UDP"
    - role: nat_router
      nat_router_local_interface: eth0
      nat_router_inet_interface: eth1
      nat_router_ip: 10.90.70.1
      nat_router_dhcp_range: "10.90.70.50,10.90.70.150,24h"
      nat_router_static_ips: "{{ chacal.nat_router_static_ips }}"
    - role: l2tp_vpn_server
      l2tp_vpn_psk: "{{ chacal.l2tp_vpn_psk }}"
      l2tp_vpn_local_ip: 10.90.70.1
      l2tp_vpn_local_ip_range: 10.90.70.200-10.90.70.250
    - role: inadyn_ddns
      inadyn_ddns_username: "{{ chacal.inadyn_ddns_username }}"
      inadyn_ddns_password: "{{ chacal.inadyn_ddns_password }}"
      inadyn_ddns_hostname: "{{ chacal.inadyn_ddns_hostname.raspigw }}"
