---
- hosts: all
  remote_user: pi
  gather_facts: yes
  become: yes

  handlers:
    - include: ../../handlers/handlers.yml

  vars:
    - hostname: raspigw
    - apt_upgrade: false
    - timezone: Europe/Helsinki
    - aws_access_key_id: "{{ chacal.aws.raspigw.access_key }}"
    - aws_secret_access_key: "{{ chacal.aws.raspigw.secret_key }}"

  vars_files:
    - secrets.yml

  roles:
    - common
    - role: unattended_upgrades
    - role: nat_router
      nat_router_local_interface: eth0
      nat_router_inet_interface: eth0
      nat_router_ip: 10.90.70.2
      nat_router_gateway: 10.90.70.1
      nat_router_dhcp_range: "10.90.70.50,10.90.70.179,6h"
      nat_router_dhcp_options:
        - "option:router,10.90.70.1"
      nat_router_static_ips: "{{ chacal.nat_router_static_ips }}"
      nat_router_dns_servers:
        - "1.1.1.1"
        - "1.0.0.1"
      nat_router_disable: true  # Disable firewall & packet forwarding