---
#
# Playbook that sets up mosquitto, InfluxDB and mqtt-to-influxdb-sender on sensor-backend.chacal.fi
#
- hosts: sensor-backend.chacal.fi
  remote_user: jihartik
  become: true

  vars_files:
    - secrets.yml

  vars:
    - aws_cli_user: root
    - aws_access_key_id: "{{ chacal.aws.home_infra_certbot.access_key }}"
    - aws_secret_access_key: "{{ chacal.aws.home_infra_certbot.secret_key }}"
    - influx_cli_auth_params: '-username {{ chacal.influxdb.admin_user.username }} -password {{ chacal.influxdb.admin_user.password }}'
    - influx_cmd: 'influx -ssl -host sensor-backend.chacal.fi'

  handlers:
    - name: Restart InfluxDB
      service: name=influxdb state=restarted

  roles:
    - role: filebeat
      filebeat_elasticsearch_hosts:
        - elastic.chacal.fi
    - role: debian_common
    - role: prometheus_node_exporter
    - role: self_monitoring
    - role: ouroboros
      ouroboros_notifier: "sendgrid://{{ chacal.sendgrid.ouroboros }}:root@{{ inventory_hostname }}/{{ chacal.ouroboros.email }}"

    - name: certbot-dns-route53
      certbot_email: "{{ chacal.certbot.email }}"
      certbot_deploy_hook: |
        #!/bin/bash
        echo "Restarting mosquitto & InfluxDB due to updated certificates.."
        mkdir -p /etc/influxdb
        cp /etc/letsencrypt/live/sensor-backend.chacal.fi/fullchain.pem /etc/influxdb/
        cp /etc/letsencrypt/live/sensor-backend.chacal.fi/privkey.pem /etc/influxdb/
        chown influxdb:influxdb /etc/influxdb/*.pem
        systemctl restart mosquitto || true
        systemctl restart influxdb || true
      tags: certbot

    - name: mqtt-server
      mqtt_server_config: |
        log_dest syslog
        log_type none
        log_type error
        log_type warning
        log_type notice
        autosave_interval 60
        max_queued_messages 500000
        password_file {{ mqtt_server_password_file }}
        allow_anonymous false
        acl_file {{ mqtt_server_acl_file }}
        persistent_client_expiration 14d

        listener 1883 localhost

        listener 8883
        cafile /etc/letsencrypt/live/sensor-backend.chacal.fi/chain.pem
        certfile /etc/letsencrypt/live/sensor-backend.chacal.fi/cert.pem
        keyfile /etc/letsencrypt/live/sensor-backend.chacal.fi/privkey.pem
        tls_version tlsv1.2
      mqtt_server_users: "{{ chacal.sensor_backend.mqtt_users }}"
      mqtt_server_acl_config: |
        user {{ chacal.sensor_backend.mqtt_users[0].username }}
        topic #
      tags: mosquitto

    - name: influxdb
      tags: influxdb

    - name: duply_to_s3
      dupply_to_s3_conf: |
        GPG_PW='{{ chacal.sensor_backend.duply.pgp_key }}'

        TARGET='s3://s3-eu-west-1.amazonaws.com/chacal-backups/sensor-backend.chacal.fi'

        SOURCE='/'

        MAX_FULLBKP_AGE=1W
        DUPL_PARAMS="$DUPL_PARAMS --full-if-older-than $MAX_FULLBKP_AGE "
        DUPL_PARAMS="$DUPL_PARAMS --s3-european-buckets --s3-use-new-style --s3-use-ia --allow-source-mismatch"
      dupply_to_s3_exclude: |
        + /var/lib/influxdb
        **
      duply_to_s3_access_key: "{{ chacal.aws.sensor_backend_backup.access_key }}"
      duply_to_s3_secret_key: "{{ chacal.aws.sensor_backend_backup.secret_key }}"

  tasks:
    - name: Configure InfluxDB to use HTTPS
      lineinfile:
        dest: /etc/influxdb/influxdb.conf
        state: present
        regexp: '^  https-enabled = '
        insertafter: '^  # https-enabled = false'
        line: '  https-enabled = true'
      notify: Restart InfluxDB
      tags: influxdb

    - name: Configure InfluxDB HTTPS certificate
      lineinfile:
        dest: /etc/influxdb/influxdb.conf
        state: present
        regexp: '^  https-certificate = '
        insertafter: '^  # https-certificate = '
        line: '  https-certificate = "/etc/influxdb/fullchain.pem"'
      notify: Restart InfluxDB
      tags: influxdb

    - name: Configure InfluxDB HTTPS private key
      lineinfile:
        dest: /etc/influxdb/influxdb.conf
        state: present
        regexp: '^  https-private-key = '
        insertafter: '^  # https-private-key = '
        line: '  https-private-key = "/etc/influxdb/privkey.pem"'
      notify: Restart InfluxDB
      tags: influxdb

    - name: Configure InfluxDB backup service to listen only on localhost
      lineinfile:
        dest: /etc/influxdb/influxdb.conf
        state: present
        regexp: '^bind-address = '
        insertafter: '^# bind-address = "127.0.0.1:8088"'
        line: 'bind-address = "localhost:8088"'
      notify: Restart InfluxDB
      tags: influxdb

    - name: Configure InfluxDB to use authentication
      lineinfile:
        dest: /etc/influxdb/influxdb.conf
        state: present
        regexp: '^  auth-enabled = '
        insertafter: '^  # auth-enabled = false'
        line: '  auth-enabled = true'
      notify: Restart InfluxDB
      tags: influxdb

    - name: Configure InfluxDB to not log HTTP requests
      lineinfile:
        dest: /etc/influxdb/influxdb.conf
        state: present
        regexp: '^  log-enabled = '
        insertafter: '^\[http\]'
        line: '  log-enabled = false'
      notify: Restart InfluxDB
      tags: influxdb

    - name: Configure InfluxDB to not log queries
      lineinfile:
        dest: /etc/influxdb/influxdb.conf
        state: present
        regexp: '^  query-log-enabled ='
        insertafter: '^  # query-log-enabled = true'
        line: '  query-log-enabled = false'
      notify: Restart InfluxDB
      tags: influxdb

    - name: Configure InfluxDB WAL fsync delay
      lineinfile:
        dest: /etc/influxdb/influxdb.conf
        state: present
        regexp: '^  wal-fsync-delay ='
        insertafter: '^  # wal-fsync-delay = "0s"'
        line: '  wal-fsync-delay = "1s"'
      notify: Restart InfluxDB
      tags: influxdb


    # Flush handlers to restart InfluxDB with SSL connection enabled
    - meta: flush_handlers


    - name: Check if InfluxDB admin user has been created
      command: '{{ influx_cmd }} -execute "SHOW USERS" {{ influx_cli_auth_params }}'
      register: influx_admin_check
      failed_when: influx_admin_check.rc > 1
      changed_when: "influx_admin_check.rc > 0"
      tags: influxdb

    - name: Create InfluxDB admin user
      command: "{{ influx_cmd }} -execute \"CREATE USER {{ chacal.influxdb.admin_user.username }} WITH PASSWORD '{{ chacal.influxdb.admin_user.password }}' WITH ALL PRIVILEGES\""
      when: influx_admin_check.changed
      tags: influxdb

    - name: Check if sensors database has been created
      command: '{{ influx_cmd }} -execute "SHOW DATABASES" {{ influx_cli_auth_params }}'
      register: influx_db_check
      changed_when: "'sensors' not in influx_db_check.stdout"
      tags: influxdb

    - name: Create InfluxDB database
      command: '{{ influx_cmd }} -execute "CREATE DATABASE sensors" {{ influx_cli_auth_params }}'
      when: influx_db_check.changed
      tags: influxdb

    - name: Check if InfluxDB regular user has been created
      command: '{{ influx_cmd }} -execute "SHOW USERS" {{ influx_cli_auth_params }}'
      register: influx_user_check
      changed_when: "chacal.influxdb.regular_user.username not in influx_user_check.stdout"
      tags: influxdb

    - name: Create InfluxDB regular user
      command: "{{ influx_cmd }} -execute \"CREATE USER {{ chacal.influxdb.regular_user.username }} WITH PASSWORD '{{ chacal.influxdb.regular_user.password }}'\" {{ influx_cli_auth_params }}"
      when: influx_user_check.changed
      tags: influxdb

    - name: Grant DB access to regular user
      command: '{{ influx_cmd }} -execute "GRANT ALL ON sensors TO {{ chacal.influxdb.regular_user.username }}" {{ influx_cli_auth_params }}'
      when: influx_user_check.changed
      tags: influxdb


    - name: Install mqtt-to-influxdb-sender
      include_role:
        name: docker-app
      vars:
        docker_regular_user: "{{ ansible_user }}"
        docker_app_name: "mqtt-to-influxdb-sender"
        docker_app_container_name: "jihartik/mqtt-to-influxdb-sender"
        docker_app_extra_params: "--init"
        docker_app_env:
          - DB_HOST=sensor-backend.chacal.fi
          - DB_PORT=8086
          - DB_USERNAME={{ chacal.influxdb.regular_user.username }}
          - DB_PASSWORD={{ chacal.influxdb.regular_user.password }}
          - DB_NAME=sensors
          - MQTT_BROKER=mqtts://sensor-backend.chacal.fi
          - MQTT_USERNAME={{ chacal.sensor_backend.mqtt_users[0].username }}
          - MQTT_PASSWORD={{ chacal.sensor_backend.mqtt_users[0].password }}
          - MQTT_CLIENT_ID=sensor-backend-influxdb-sender