- import_playbook: fujari.chacal.fi.yml
- import_playbook: haukkakallio.chacal.fi.yml
- import_playbook: homeassistant.chacal.fi.yml
- import_playbook: mini.chacal.fi.yml
- import_playbook: minio.chacal.fi.yml
- import_playbook: printer.chacal.fi.yml
- import_playbook: viessmann.chacal.fi.yml
