{
 "title": "Nihtimäki",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Downstairs closet",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Downstairs closet (S218)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "S218" }
     ]
    }
   ]
  },
  {
   "title": "Living room",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Living room (S205)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "S205" }
     ]
    }
   ]
  },
  {
   "title": "Upstairs closet",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Upstairs closet (S217)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "S217" }
     ]
    }
   ]
  },
  {
   "title": "Upstairs bathroom",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Upstairs bathroom (S216)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "S216" }
     ]
    }
   ]
  },
  {
   "title": "Small storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Small storage (S219)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "S219" }
     ]
    }
   ]
  },
  {
   "title": "Big storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Big storage (S220)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "S220" }
     ]
    }
   ]
  },
  {
   "title": "Humidities",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Living room (S205)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S205'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Living room (S205)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1671796277) AND dt <= toDateTime(1671882677)\n    AND instance = 'S205'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Upstairs bathroom (S216)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S216'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Upstairs bathroom (S216)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1671796277) AND dt <= toDateTime(1671882677)\n    AND instance = 'S216'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Upstairs closet (S217)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S217'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Upstairs closet (S217)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1671796277) AND dt <= toDateTime(1671882677)\n    AND instance = 'S217'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Downstairs closet (S218)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S218'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Downstairs closet (S218)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1671796277) AND dt <= toDateTime(1671882677)\n    AND instance = 'S218'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Small storage (S219)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S219'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Small storage (S219)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1671796277) AND dt <= toDateTime(1671882677)\n    AND instance = 'S219'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Big storage (S220)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S220'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Big storage (S220)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1671796277) AND dt <= toDateTime(1671882677)\n    AND instance = 'S220'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Sensor voltages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S205\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S205'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S205\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1671796436) AND dt <= toDateTime(1671882836)\n    AND instance = 'S205'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S216\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S216'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S216\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1671796436) AND dt <= toDateTime(1671882836)\n    AND instance = 'S216'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S217\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S217'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S217\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1671796436) AND dt <= toDateTime(1671882836)\n    AND instance = 'S217'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S218\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S218'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S218\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1671796436) AND dt <= toDateTime(1671882836)\n    AND instance = 'S218'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S219\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S219'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S219\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1671796436) AND dt <= toDateTime(1671882836)\n    AND instance = 'S219'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S220\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S220'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S220\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1671796436) AND dt <= toDateTime(1671882836)\n    AND instance = 'S220'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S205\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S205'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S205\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1671796396) AND dt <= toDateTime(1671882796)\n    AND instance = 'S205'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S216\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S216'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S216\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1671796396) AND dt <= toDateTime(1671882796)\n    AND instance = 'S216'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S217\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S217'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S217\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1671796396) AND dt <= toDateTime(1671882796)\n    AND instance = 'S217'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S218\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S218'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S218\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1671796396) AND dt <= toDateTime(1671882796)\n    AND instance = 'S218'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S219\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S219'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S219\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1671796396) AND dt <= toDateTime(1671882796)\n    AND instance = 'S219'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S220\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S220'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S220\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1671796396) AND dt <= toDateTime(1671882796)\n    AND instance = 'S220'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Living room (S205)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S205'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Living room (S205)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1671796472) AND dt <= toDateTime(1671882872)\n    AND instance = 'S205'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Upstairs bathroom (S216)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S216'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Upstairs bathroom (S216)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1671796472) AND dt <= toDateTime(1671882872)\n    AND instance = 'S216'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Downstairs closet (S218)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S218'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Downstairs closet (S218)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1671796472) AND dt <= toDateTime(1671882872)\n    AND instance = 'S218'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Upstairs closet (S217)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S217'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Upstairs closet (S217)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1671796472) AND dt <= toDateTime(1671882872)\n    AND instance = 'S217'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Small storage (S219)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S219'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Small storage (S219)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1671796472) AND dt <= toDateTime(1671882872)\n    AND instance = 'S219'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Big storage (S220)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S220'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Big storage (S220)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1671796472) AND dt <= toDateTime(1671882872)\n    AND instance = 'S220'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  }
 ]
}