{
 "title": "Freya",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "House bat voltage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensorVoltage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "C400" }
     ]
    }
   ]
  },
  {
   "title": "House bat current",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "C400" }
     ]
    }
   ]
  },
  {
   "title": "House bat state",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ampHours",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "C400" }
     ]
    }
   ]
  },
  {
   "title": "Water",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tankLevel",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "W100" }
     ]
    }
   ]
  },
  {
   "title": "Air pressure",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "pressurehpa",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pressure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "S216" }
     ]
    }
   ]
  },
  {
   "title": "4G Signal",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 2, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "level",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "H101" }
     ]
    }
   ]
  },
  {
   "title": "House battery SoC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "amph" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'ampHours')]) AS \"C400\"\nFROM $table\nWHERE\n    $timeFilter\n    AND indexOf(metric_names, 'ampHours') > 0\n    AND instance = 'C400'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S216\" FROM default.measurements WHERE     dt >= toDateTime(1588533223)     AND instance = 'S216' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Saloon",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "alias": "Saloon (S216)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "S216" }
     ]
    }
   ]
  },
  {
   "title": "Fwd cabin",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "alias": "Fwd cabin (S218)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "S218" }
     ]
    }
   ]
  },
  {
   "title": "Aft cabin",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "alias": "Aft cabin (S205)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "S205" }
     ]
    }
   ]
  },
  {
   "title": "Outside",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "alias": "Outside (S219)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "S219" }
     ]
    }
   ]
  },
  {
   "title": "Mast",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "alias": "Mast (S217)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "S217" }
     ]
    }
   ]
  },
  {
   "title": "House battery",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Voltage\"\nFROM $table\nWHERE\n    $timeFilter\n    AND indexOf(metric_names, 'sensorVoltage') > 0\n    AND instance = 'C400'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S216\" FROM default.measurements WHERE     dt >= toDateTime(1588533473)     AND instance = 'S216' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'current')]) AS \"Current\"\nFROM $table\nWHERE\n    $timeFilter\n    AND indexOf(metric_names, 'current') > 0\n    AND instance = 'C400'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S217\" FROM default.measurements WHERE     dt >= toDateTime(1588533583)     AND instance = 'S217' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Water tank",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'tankLevel')]) AS \"Water\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'W100'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Alternator (T100)\" FROM default.measurements WHERE     dt >= toDateTime(1588364795)     AND instance = 'T100' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Air pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'pressure')]) AS \"Saloon (S216)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S216'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S216\" FROM default.measurements WHERE     dt >= toDateTime(1588533583)     AND instance = 'S216' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Alternator",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Alternator (T100)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'T100'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'ampHours')]) AS \"C400\" FROM default.measurements WHERE     dt >= toDateTime(1588364405)     AND indexOf(metric_names, 'ampHours') > 0     AND instance = 'C400' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'level')]) AS \"Alternator fan (100)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = '100'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'level')]) AS \"Alternator fan (100)\" FROM default.measurements WHERE     dt >= toDateTime(1588364795)     AND instance = '100' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Aft cabin (S205)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S205'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"D102\" FROM default.measurements WHERE     dt >= toDateTime(1588332252)     AND instance = 'D102' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Saloon (S216)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S216'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S216\" FROM default.measurements WHERE     dt >= toDateTime(1588332252)     AND instance = 'S216' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Fwd cabin (S218)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S218'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S217\" FROM default.measurements WHERE     dt >= toDateTime(1588332252)     AND instance = 'S217' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Mast (S217)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S217'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S218\" FROM default.measurements WHERE     dt >= toDateTime(1588332252)     AND instance = 'S218' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Outside (S219)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S219'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"T100\" FROM default.measurements WHERE     dt >= toDateTime(1588332252)     AND instance = 'T100' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Humidities",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Aft cabin (S205)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S205'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"D102\" FROM default.measurements WHERE     dt >= toDateTime(1588332562)     AND instance = 'D102' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Saloon (S216)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S216'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S216\" FROM default.measurements WHERE     dt >= toDateTime(1588332562)     AND instance = 'S216' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Mast (S217)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S217'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S218\" FROM default.measurements WHERE     dt >= toDateTime(1588332562)     AND instance = 'S218' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Fwd cabin (S218)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S218'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S217\" FROM default.measurements WHERE     dt >= toDateTime(1588332562)     AND instance = 'S217' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Outside (S219)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S219'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"T100\" FROM default.measurements WHERE     dt >= toDateTime(1588332562)     AND instance = 'T100' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S205\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S205'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S205\" FROM default.measurements WHERE     dt >= toDateTime(1591280230)     AND instance = 'S205' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S216\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S216'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S216\" FROM default.measurements WHERE     dt >= toDateTime(1591280230)     AND instance = 'S216' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S217\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S217'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S217\" FROM default.measurements WHERE     dt >= toDateTime(1591280230)     AND instance = 'S217' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S218\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S218'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S218\" FROM default.measurements WHERE     dt >= toDateTime(1591280230)     AND instance = 'S218' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S219\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S219'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S219\" FROM default.measurements WHERE     dt >= toDateTime(1591280230)     AND instance = 'S219' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"T100\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'T100'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"T100\" FROM default.measurements WHERE     dt >= toDateTime(1591280230)     AND instance = 'T100' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"W100\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'W100'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"W100\" FROM default.measurements WHERE     dt >= toDateTime(1591280230)     AND instance = 'W100' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"P311\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'P311'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"P311\" FROM default.measurements WHERE     dt >= toDateTime(1591280230)     AND instance = 'P311' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"P312\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'P312'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"P312\" FROM default.measurements WHERE     dt >= toDateTime(1591280230)     AND instance = 'P312' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Sensor voltages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S205\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S205'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S205\" FROM default.measurements WHERE     dt >= toDateTime(1591280295)     AND instance = 'S205' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S216\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S216'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S216\" FROM default.measurements WHERE     dt >= toDateTime(1591280295)     AND instance = 'S216' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S217\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S217'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S217\" FROM default.measurements WHERE     dt >= toDateTime(1591280295)     AND instance = 'S217' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S218\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S218'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S218\" FROM default.measurements WHERE     dt >= toDateTime(1591280295)     AND instance = 'S218' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S219\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S219'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S219\" FROM default.measurements WHERE     dt >= toDateTime(1591280295)     AND instance = 'S219' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"T100\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'T100'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"T100\" FROM default.measurements WHERE     dt >= toDateTime(1591280295)     AND instance = 'T100' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"W100\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'W100'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"W100\" FROM default.measurements WHERE     dt >= toDateTime(1591280295)     AND instance = 'W100' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"D102\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D102'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"D102\" FROM default.measurements WHERE     dt >= toDateTime(1591280295)     AND instance = 'D102' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"D103\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D103'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"D103\" FROM default.measurements WHERE     dt >= toDateTime(1591280295)     AND instance = 'D103' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"D105\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D105'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"D105\" FROM default.measurements WHERE     dt >= toDateTime(1591280295)     AND instance = 'D105' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"D106\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D106'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"D106\" FROM default.measurements WHERE     dt >= toDateTime(1591280295)     AND instance = 'D106' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"P311\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'P311'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"P311\" FROM default.measurements WHERE     dt >= toDateTime(1591280295)     AND instance = 'P311' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"P312\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'P312'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"P312\" FROM default.measurements WHERE     dt >= toDateTime(1591280295)     AND instance = 'P312' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Motion detection",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    max(metric_values[indexOf(metric_names, 'motionDetected')]) AS \"Nav table (P311)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'P311'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     max(metric_values[indexOf(metric_names, 'motionDetected')]) AS \"Nav table (P311)\" FROM default.measurements WHERE     dt >= toDateTime(1591280852)     AND instance = 'P311' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    max(metric_values[indexOf(metric_names, 'motionDetected')]) AS \"Saloon (P312)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'P312'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     max(metric_values[indexOf(metric_names, 'motionDetected')]) AS \"Saloon (P312)\" FROM default.measurements WHERE     dt >= toDateTime(1591280852)     AND instance = 'P312' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  }
 ]
}