{
 "title": "Nihtimäki",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Electricity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Electricity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    count(metric_values[indexOf(metric_names, 'impulse')]) * 30 / 1000 AS \"kW\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'I100'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     count(metric_values[indexOf(metric_names, 'impulse')]) * 30 / 1000 AS \"kW\" FROM default.measurements WHERE     dt >= toDateTime(1586193314)     AND instance = 'I100' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Electricity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    count(metric_values[indexOf(metric_names, 'impulse')]) / 1000 AS \"kW\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'I100'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 3600) * 3600) * 1000 as t,     count(metric_values[indexOf(metric_names, 'impulse')]) / 1000 AS \"kW\" FROM default.measurements WHERE     dt >= toDateTime(1586193465)     AND instance = 'I100' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Electricity",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toUInt32(toStartOfDay(dt)) * 1000 as t,\n    count(metric_values[indexOf(metric_names, 'impulse')]) / 1000 AS \"kWh\"\nFROM $table\nWHERE\n    dt > now() - INTERVAL 7 DAY\n    AND instance = 'I100'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    toUInt32(toStartOfDay(dt)) * 1000 as t,\n    count(metric_values[indexOf(metric_names, 'impulse')]) / 1000 AS \"kWh\"\nFROM default.measurements\nWHERE\n    dt > now() - INTERVAL 7 DAY\n    AND instance = 'I100'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  { "title": "Temperatures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Outside",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Outside (S222)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "S222" }
     ]
    }
   ]
  },
  {
   "title": "Car",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Car (S215)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "S215" }
     ]
    }
   ]
  },
  {
   "title": "Big storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Big storage (S220)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "S220" }
     ]
    }
   ]
  },
  {
   "title": "Small storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Small storage (S219)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "S219" }
     ]
    }
   ]
  },
  {
   "title": "Sauna",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Sauna (S209)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "S209" }
     ]
    }
   ]
  },
  {
   "title": "Freezer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Freezer (S218)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "S218" }
     ]
    }
   ]
  },
  { "title": "Downstairs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Living room (S205)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S205'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Living room (S205)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677960926) AND dt <= toDateTime(1678047326)\n    AND instance = 'S205'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Laura's room (S210)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S210'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Laura's room (S210)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677960926) AND dt <= toDateTime(1678047326)\n    AND instance = 'S210'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Bedroom (S211)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S211'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Bedroom (S211)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677960926) AND dt <= toDateTime(1678047326)\n    AND instance = 'S211'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Food closet (S212)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S212'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Food closet (S212)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677960926) AND dt <= toDateTime(1678047326)\n    AND instance = 'S212'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Tech room (S213)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S213'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Tech room (S213)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677960926) AND dt <= toDateTime(1678047326)\n    AND instance = 'S213'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"WC, downstairs (S214)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S214'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"WC, downstairs (S214)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677960926) AND dt <= toDateTime(1678047326)\n    AND instance = 'S214'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Closet, downstairs (S221)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S221'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Closet, downstairs (S221)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677960926) AND dt <= toDateTime(1678047326)\n    AND instance = 'S221'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Humidities",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Living room (S205)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S205'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Living room (S205)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677961285) AND dt <= toDateTime(1678047685)\n    AND instance = 'S205'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Laura's room (S210)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S210'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Laura's room (S210)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677961285) AND dt <= toDateTime(1678047685)\n    AND instance = 'S210'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Bedroom (S211)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S211'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Bedroom (S211)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677961285) AND dt <= toDateTime(1678047685)\n    AND instance = 'S211'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Food closet (S212)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S212'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Food closet (S212)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677961285) AND dt <= toDateTime(1678047685)\n    AND instance = 'S212'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Tech room (S213)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S213'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Tech room (S213)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677961285) AND dt <= toDateTime(1678047685)\n    AND instance = 'S213'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"WC, downstairs (S214)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S214'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"WC, downstairs (S214)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677961285) AND dt <= toDateTime(1678047685)\n    AND instance = 'S214'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Closet, downstairs (S221)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S221'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Closet, downstairs (S221)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677961285) AND dt <= toDateTime(1678047685)\n    AND instance = 'S221'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  { "title": "Downstairs health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Sensor voltages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Livingroom (S205)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S205'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Livingroom (S205)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677961598) AND dt <= toDateTime(1678047998)\n    AND instance = 'S205'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Laura's room (S210)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S210'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Laura's room (S210)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677961598) AND dt <= toDateTime(1678047998)\n    AND instance = 'S210'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Bedroom (S211)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S211'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Bedroom (S211)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677961598) AND dt <= toDateTime(1678047998)\n    AND instance = 'S211'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Food closet (S212)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S212'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Food closet (S212)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677961598) AND dt <= toDateTime(1678047998)\n    AND instance = 'S212'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Tech room (S213\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S213'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Tech room (S213\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677961598) AND dt <= toDateTime(1678047998)\n    AND instance = 'S213'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"WC, downstairs (S214)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S214'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"WC, downstairs (S214)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677961598) AND dt <= toDateTime(1678047998)\n    AND instance = 'S214'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Closet, downstairs (S221)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S221'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Closet, downstairs (S221)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677961598) AND dt <= toDateTime(1678047998)\n    AND instance = 'S221'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Livingroom (S205)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S205'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Livingroom (S205)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677961742) AND dt <= toDateTime(1678048142)\n    AND instance = 'S205'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Laura's room (S210)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S210'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Laura's room (S210)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677961742) AND dt <= toDateTime(1678048142)\n    AND instance = 'S210'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Bedroom (S211)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S211'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Bedroom (S211)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677961742) AND dt <= toDateTime(1678048142)\n    AND instance = 'S211'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Food closet (S212)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S212'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Food closet (S212)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677961742) AND dt <= toDateTime(1678048142)\n    AND instance = 'S212'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Tech room (S213)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S213'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Tech room (S213)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677961742) AND dt <= toDateTime(1678048142)\n    AND instance = 'S213'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"WC, downstairs (S214)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S214'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"WC, downstairs (S214)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677961742) AND dt <= toDateTime(1678048142)\n    AND instance = 'S214'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Closet, downstairs (S221)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S221'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Closet, downstairs (S221)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677961742) AND dt <= toDateTime(1678048142)\n    AND instance = 'S221'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  { "title": "Upstairs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Jouni's room (S201)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S201'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Jouni's room (S201)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962041) AND dt <= toDateTime(1678048441)\n    AND instance = 'S201'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Venla's room (S202)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S202'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Venla's room (S202)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962041) AND dt <= toDateTime(1678048441)\n    AND instance = 'S202'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Oona's room (S203)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S203'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Oona's room (S203)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962041) AND dt <= toDateTime(1678048441)\n    AND instance = 'S203'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Elias' room (S204)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S204'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Elias' room (S204)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962041) AND dt <= toDateTime(1678048441)\n    AND instance = 'S204'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Utility room (S206)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S206'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Utility room (S206)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962041) AND dt <= toDateTime(1678048441)\n    AND instance = 'S206'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"WC, upstairs (S208)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S208'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"WC, upstairs (S208)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962041) AND dt <= toDateTime(1678048441)\n    AND instance = 'S208'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Bathroom (S216)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S216'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Bathroom (S216)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962041) AND dt <= toDateTime(1678048441)\n    AND instance = 'S216'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Closet, upstairs (S217)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S217'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Closet, upstairs (S217)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962041) AND dt <= toDateTime(1678048441)\n    AND instance = 'S217'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Humidities",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Jouni's room (S201)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S201'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Jouni's room (S201)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962211) AND dt <= toDateTime(1678048611)\n    AND instance = 'S201'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Venla's room (S202)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S202'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Venla's room (S202)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962211) AND dt <= toDateTime(1678048611)\n    AND instance = 'S202'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Oona's room (S203)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S203'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Oona's room (S203)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962211) AND dt <= toDateTime(1678048611)\n    AND instance = 'S203'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Elias' room (S204)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S204'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Elias' room (S204)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962211) AND dt <= toDateTime(1678048611)\n    AND instance = 'S204'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Utility room (S206)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S206'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Utility room (S206)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962211) AND dt <= toDateTime(1678048611)\n    AND instance = 'S206'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"WC, upstairs (S208)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S208'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"WC, upstairs (S208)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962211) AND dt <= toDateTime(1678048611)\n    AND instance = 'S208'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Bathroom (S216)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S216'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Bathroom (S216)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962211) AND dt <= toDateTime(1678048611)\n    AND instance = 'S216'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Closet, upstairs (S217)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S217'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Closet, upstairs (S217)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962211) AND dt <= toDateTime(1678048611)\n    AND instance = 'S217'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  { "title": "Downstairs health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Sensor voltages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Jouni's room (S201)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S201'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Jouni's room (S201)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962419) AND dt <= toDateTime(1678048819)\n    AND instance = 'S201'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Venla's room (S202)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S202'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Venla's room (S202)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962419) AND dt <= toDateTime(1678048819)\n    AND instance = 'S202'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Oona's room (S203)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S203'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Oona's room (S203)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962419) AND dt <= toDateTime(1678048819)\n    AND instance = 'S203'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Elias' room (S204)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S204'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Elias' room (S204)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962419) AND dt <= toDateTime(1678048819)\n    AND instance = 'S204'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Utility room (S206)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S206'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Utility room (S206)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962419) AND dt <= toDateTime(1678048819)\n    AND instance = 'S206'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"WC, upstairs (S208)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S208'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"WC, upstairs (S208)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962419) AND dt <= toDateTime(1678048819)\n    AND instance = 'S208'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Bathroom (S216)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S216'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Bathroom (S216)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962419) AND dt <= toDateTime(1678048819)\n    AND instance = 'S216'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Closet, upstairs (S217)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S217'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Closet, upstairs (S217)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962419) AND dt <= toDateTime(1678048819)\n    AND instance = 'S217'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Jouni's room (S201)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S201'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Jouni's room (S201)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962554) AND dt <= toDateTime(1678048954)\n    AND instance = 'S201'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Venla's room (S202)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S202'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Venla's room (S202)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962554) AND dt <= toDateTime(1678048954)\n    AND instance = 'S202'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Oona's room (S203)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S203'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Oona's room (S203)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962554) AND dt <= toDateTime(1678048954)\n    AND instance = 'S203'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Elias' room (S204)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S204'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Elias' room (S204)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962554) AND dt <= toDateTime(1678048954)\n    AND instance = 'S204'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Utility room (S206)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S206'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Utility room (S206)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962554) AND dt <= toDateTime(1678048954)\n    AND instance = 'S206'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"WC, upstairs (S208)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S208'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"WC, upstairs (S208)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962554) AND dt <= toDateTime(1678048954)\n    AND instance = 'S208'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Bathroom (S216)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S216'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Bathroom (S216)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962554) AND dt <= toDateTime(1678048954)\n    AND instance = 'S216'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Closet, upstairs (S217)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S217'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Closet, upstairs (S217)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962554) AND dt <= toDateTime(1678048954)\n    AND instance = 'S217'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  { "title": "Outside", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Outside (S222)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S222'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Outside (S222)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962716) AND dt <= toDateTime(1678049116)\n    AND instance = 'S222'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Car (S215)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S215'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Car (S215)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962716) AND dt <= toDateTime(1678049116)\n    AND instance = 'S215'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Big storage (S220)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S220'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Big storage (S220)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962716) AND dt <= toDateTime(1678049116)\n    AND instance = 'S220'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Small storage (S219)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S219'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Small storage (S219)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962716) AND dt <= toDateTime(1678049116)\n    AND instance = 'S219'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Humidities",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Outside (S222)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S222'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Outside (S222)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962814) AND dt <= toDateTime(1678049214)\n    AND instance = 'S222'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Car (S215)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S215'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Car (S215)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962814) AND dt <= toDateTime(1678049214)\n    AND instance = 'S215'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Big storage (S220)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S220'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Big storage (S220)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962814) AND dt <= toDateTime(1678049214)\n    AND instance = 'S220'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Small storage (S219)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S219'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Small storage (S219)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962814) AND dt <= toDateTime(1678049214)\n    AND instance = 'S219'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'pressure')]) AS \"Outside (S222)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S222'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'pressure')]) AS \"Outside (S222)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677963174) AND dt <= toDateTime(1678049574)\n    AND instance = 'S222'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'pressure')]) AS \"Car (S215)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S215'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'pressure')]) AS \"Car (S215)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677963174) AND dt <= toDateTime(1678049574)\n    AND instance = 'S215'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  { "title": "Outside health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Sensor voltages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Outside (S222)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S222'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Outside (S222)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962927) AND dt <= toDateTime(1678049327)\n    AND instance = 'S222'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Car (S215)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S215'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Car (S215)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962927) AND dt <= toDateTime(1678049327)\n    AND instance = 'S215'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Big storage (S220)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S220'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Big storage (S220)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962927) AND dt <= toDateTime(1678049327)\n    AND instance = 'S220'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Small storage (S219)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S219'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"Small storage (S219)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1677962927) AND dt <= toDateTime(1678049327)\n    AND instance = 'S219'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Outside (S222)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S222'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Outside (S222)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1679564850) AND dt <= toDateTime(1679651250)\n    AND instance = 'S222'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Car (S215)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S215'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Car (S215)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1679564850) AND dt <= toDateTime(1679651250)\n    AND instance = 'S215'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Big storage (S220)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S220'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Big storage (S220)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1679564850) AND dt <= toDateTime(1679651250)\n    AND instance = 'S220'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Small storage (S219)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S219'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"Small storage (S219)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1679564850) AND dt <= toDateTime(1679651250)\n    AND instance = 'S219'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  }
 ]
}