{
 "title": "Haukkakallio",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Electricity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Electricity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    count(metric_values[indexOf(metric_names, 'impulse')]) * 30 / 1000 AS \"kW\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'I100'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     count(metric_values[indexOf(metric_names, 'impulse')]) * 30 / 1000 AS \"kW\" FROM default.measurements WHERE     dt >= toDateTime(1586193314)     AND instance = 'I100' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Electricity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    count(metric_values[indexOf(metric_names, 'impulse')]) / 1000 AS \"kW\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'I100'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 3600) * 3600) * 1000 as t,     count(metric_values[indexOf(metric_names, 'impulse')]) / 1000 AS \"kW\" FROM default.measurements WHERE     dt >= toDateTime(1586193465)     AND instance = 'I100' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Electricity",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toUInt32(toStartOfDay(dt)) * 1000 as t,\n    count(metric_values[indexOf(metric_names, 'impulse')]) / 1000 AS \"kWh\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'I100'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'thread_latestRssi')]) AS \"RSSI (latest)\" FROM default.measurements WHERE     dt >= toDateTime(1586195243)     AND instance = 'D104' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Upstairs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Livingroom (S206)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S206'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Livingroom (S206)\" FROM default.measurements WHERE     dt >= toDateTime(1586182691)     AND instance = 'S206' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Kitchen (S207)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S207'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Kitchen (S207)\" FROM default.measurements WHERE     dt >= toDateTime(1586182691)     AND instance = 'S207' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Storageroom (S208)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S208'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Storageroom (S208)\" FROM default.measurements WHERE     dt >= toDateTime(1586182691)     AND instance = 'S208' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Livingroom (S206)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S206'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'thread_avgRssi')]) AS \"RSSI (avg)\" FROM default.measurements WHERE     dt >= toDateTime(1586199408)     AND instance = 'D104' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Kitchen (S207)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S207'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'thread_latestRssi')]) AS \"RSSI (latest)\" FROM default.measurements WHERE     dt >= toDateTime(1586202301)     AND instance = 'D104' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Storageroom (S208)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S208'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'thread_linkQualityIn')]) AS \"Link quality in\" FROM default.measurements WHERE     dt >= toDateTime(1586202301)     AND instance = 'D104' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Downstairs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Kids room (S201)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S201'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S215\" FROM default.measurements WHERE     dt >= toDateTime(1588331734)     AND instance = 'S215' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Study (S202)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S202'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"P300\" FROM default.measurements WHERE     dt >= toDateTime(1588331734)     AND instance = 'P300' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Master bedroom (S203)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S203'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"P301\" FROM default.measurements WHERE     dt >= toDateTime(1588331734)     AND instance = 'P301' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Guestroom (S209)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S209'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"P302\" FROM default.measurements WHERE     dt >= toDateTime(1588331734)     AND instance = 'P302' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"WC (S212)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S212'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"P303\" FROM default.measurements WHERE     dt >= toDateTime(1588331734)     AND instance = 'P303' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Kids room (S201)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S201'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'thread_avgRssi')]) AS \"RSSI (avg)\" FROM default.measurements WHERE     dt >= toDateTime(1588331774)     AND instance = 'D104' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Study (S202)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S202'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'thread_latestRssi')]) AS \"RSSI (latest)\" FROM default.measurements WHERE     dt >= toDateTime(1588331774)     AND instance = 'D104' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Master bedroom (S203)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S203'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'thread_linkQualityIn')]) AS \"Link quality in\" FROM default.measurements WHERE     dt >= toDateTime(1588331774)     AND instance = 'D104' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Guest room (S209)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S209'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'thread_linkQualityOut')]) AS \"Link quality out\" FROM default.measurements WHERE     dt >= toDateTime(1588331774)     AND instance = 'D104' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"WC (S212)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S212'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"P303\" FROM default.measurements WHERE     dt >= toDateTime(1588331774)     AND instance = 'P303' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Outside",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Outside, balcony (S213)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S213'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Outside, balcony (S213)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1634973249) AND dt <= toDateTime(1635059649)\n    AND instance = 'S213'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Outside, backyard (S222)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S222'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Outside, backyard (S222)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1634973249) AND dt <= toDateTime(1635059649)\n    AND instance = 'S222'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Outside, balcony (S213)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S213'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Outside, balcony (S213)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1634973272) AND dt <= toDateTime(1635059672)\n    AND instance = 'S213'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Outside, backyard (S222)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S222'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Outside, backyard (S222)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1634973272) AND dt <= toDateTime(1635059672)\n    AND instance = 'S222'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'pressure')]) AS \"Outside, balcony (S213)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S213'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'pressure')]) AS \"Outside, balcony (S213)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1634973290) AND dt <= toDateTime(1635059690)\n    AND instance = 'S213'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'pressure')]) AS \"Outside, backyard (S222)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S222'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'pressure')]) AS \"Outside, backyard (S222)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1634973290) AND dt <= toDateTime(1635059690)\n    AND instance = 'S222'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Ventilation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Outside air (S210)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S210'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'pressure')]) AS \"Outside (S213)\" FROM default.measurements WHERE     dt >= toDateTime(1586186605)     AND instance = 'S213' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'temperature')]) AS \"Pre-heated air (S211)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S211'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Study (S202)\" FROM default.measurements WHERE     dt >= toDateTime(1586186605)     AND instance = 'S202' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Outside air (S210)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S210'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'pressure')]) AS \"Outside (S213)\" FROM default.measurements WHERE     dt >= toDateTime(1586186686)     AND instance = 'S213' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Pre-heated air (S211)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S211'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'humidity')]) AS \"Pre-heated air (S211)\" FROM default.measurements WHERE     dt >= toDateTime(1586186826)     AND instance = 'S211' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Sensor health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S201\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S201'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S201\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1607620117)\n    AND instance = 'S201'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S202\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S202'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S202\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1607620117)\n    AND instance = 'S202'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S203\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S203'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S203\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1607620117)\n    AND instance = 'S203'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S204\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S204'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S204\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1607620117)\n    AND instance = 'S204'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S206\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S206'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S206\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1607620117)\n    AND instance = 'S206'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S207\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S207'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S207\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1607620117)\n    AND instance = 'S207'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S208\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S208'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S208\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1610916626)\n    AND instance = 'S208'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S209\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S209'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S209\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1610916626)\n    AND instance = 'S209'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S210\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S210'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S210\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1610916626)\n    AND instance = 'S210'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S211\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S211'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S211\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1610916626)\n    AND instance = 'S211'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S212\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S212'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S212\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1610916626)\n    AND instance = 'S212'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S213\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S213'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S213\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1610916626)\n    AND instance = 'S213'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S214\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S214'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S214\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1610916626)\n    AND instance = 'S214'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S215\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S215'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S215\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1610916626)\n    AND instance = 'S215'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S222\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S222'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"S222\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1610916626)\n    AND instance = 'S222'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"P300\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'P300'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"P300\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1607620109)\n    AND instance = 'P300'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"P301\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'P301'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"P301\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1607620109)\n    AND instance = 'P301'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"P302\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'P302'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"P302\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1607620109)\n    AND instance = 'P302'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"P303\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'P303'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"P303\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1607620109)\n    AND instance = 'P303'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"P304\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'P304'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"P304\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1607620109)\n    AND instance = 'P304'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"P306\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'P306'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"P306\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1607620109)\n    AND instance = 'P306'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"P307\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'P307'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"P307\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1607620109)\n    AND instance = 'P307'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"P308\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'P308'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"P308\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1607620109)\n    AND instance = 'P308'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"P309\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'P309'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"P309\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1607620109)\n    AND instance = 'P309'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"P310\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'P310'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"P310\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1607620109)\n    AND instance = 'P310'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S201\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S201'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'thread_avgRssi')]) AS \"RSSI (avg)\" FROM default.measurements WHERE     dt >= toDateTime(1588331904)     AND instance = 'D104' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S202\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S202'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'thread_latestRssi')]) AS \"RSSI (latest)\" FROM default.measurements WHERE     dt >= toDateTime(1588331904)     AND instance = 'D104' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S203\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S203'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'thread_linkQualityIn')]) AS \"Link quality in\" FROM default.measurements WHERE     dt >= toDateTime(1588331904)     AND instance = 'D104' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S204\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S204'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'thread_linkQualityOut')]) AS \"Link quality out\" FROM default.measurements WHERE     dt >= toDateTime(1588331904)     AND instance = 'D104' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S206\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S206'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"P304\" FROM default.measurements WHERE     dt >= toDateTime(1588331904)     AND instance = 'P304' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S207\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S207'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"P306\" FROM default.measurements WHERE     dt >= toDateTime(1588331904)     AND instance = 'P306' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S208\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S208'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S208\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1610870101)\n    AND instance = 'S208'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S209\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S209'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S209\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1610870101)\n    AND instance = 'S209'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S210\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S210'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S210\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1610870101)\n    AND instance = 'S210'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S211\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S211'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S211\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1610870101)\n    AND instance = 'S211'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S212\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S212'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S212\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1610870101)\n    AND instance = 'S212'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S213\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S213'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S213\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1610870101)\n    AND instance = 'S213'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S214\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S214'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S214\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1610870101)\n    AND instance = 'S214'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S215\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S215'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S215\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1610870101)\n    AND instance = 'S215'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S222\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'S222'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"S222\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1610870101)\n    AND instance = 'S222'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"P300\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'P300'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"P300\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1607619998)\n    AND instance = 'P300'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"P301\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'P301'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"P301\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1607619998)\n    AND instance = 'P301'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"P302\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'P302'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"P302\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1607619998)\n    AND instance = 'P302'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"P303\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'P303'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"P303\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1607619998)\n    AND instance = 'P303'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"P304\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'P304'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"P304\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1607619998)\n    AND instance = 'P304'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"P306\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'P306'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"P306\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1607619998)\n    AND instance = 'P306'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"P307\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'P307'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"P307\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1607619998)\n    AND instance = 'P307'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"P308\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'P308'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"P308\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1607619998)\n    AND instance = 'P308'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"P309\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'P309'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"P309\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1607619998)\n    AND instance = 'P309'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"P310\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'P310'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'rssi')]) AS \"P310\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1607619998)\n    AND instance = 'P310'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Thread Display D101",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'thread_avgRssi')]) AS \"RSSI (avg)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D101'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'thread_avgRssi')]) AS \"RSSI (avg)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1602333198)\n    AND instance = 'D101'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'thread_latestRssi')]) AS \"RSSI (latest)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D101'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'thread_latestRssi')]) AS \"RSSI (latest)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1602333198)\n    AND instance = 'D101'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'thread_linkQualityIn')]) AS \"Link quality in\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D101'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'thread_linkQualityIn')]) AS \"Link quality in\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1602333198)\n    AND instance = 'D101'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'thread_linkQualityOut')]) AS \"Link quality out\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D101'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'thread_linkQualityOut')]) AS \"Link quality out\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1602333198)\n    AND instance = 'D101'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Thread Display D104",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'thread_avgRssi')]) AS \"RSSI (avg)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D104'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'thread_avgRssi')]) AS \"RSSI (avg)\" FROM default.measurements WHERE     dt >= toDateTime(1586236108)     AND instance = 'D104' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'thread_latestRssi')]) AS \"RSSI (latest)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D104'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'thread_latestRssi')]) AS \"RSSI (latest)\" FROM default.measurements WHERE     dt >= toDateTime(1586236108)     AND instance = 'D104' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'thread_linkQualityIn')]) AS \"Link quality in\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D104'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'thread_linkQualityIn')]) AS \"Link quality in\" FROM default.measurements WHERE     dt >= toDateTime(1586236108)     AND instance = 'D104' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'thread_linkQualityOut')]) AS \"Link quality out\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D104'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 120) * 120) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'thread_linkQualityOut')]) AS \"Link quality out\" FROM default.measurements WHERE     dt >= toDateTime(1586202301)     AND instance = 'D104' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Thread Display D107",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'thread_avgRssi')]) AS \"RSSI (avg)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D107'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'thread_avgRssi')]) AS \"RSSI (avg)\" FROM default.measurements WHERE     dt >= toDateTime(1597297388)     AND instance = 'D107' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'thread_latestRssi')]) AS \"RSSI (latest)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D107'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'thread_latestRssi')]) AS \"RSSI (latest)\" FROM default.measurements WHERE     dt >= toDateTime(1597297388)     AND instance = 'D107' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'thread_linkQualityIn')]) AS \"Link quality in\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D107'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'thread_linkQualityIn')]) AS \"Link quality in\" FROM default.measurements WHERE     dt >= toDateTime(1597297388)     AND instance = 'D107' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'thread_linkQualityOut')]) AS \"Link quality out\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D107'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,     avg(metric_values[indexOf(metric_names, 'thread_linkQualityOut')]) AS \"Link quality out\" FROM default.measurements WHERE     dt >= toDateTime(1597297388)     AND instance = 'D107' GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Thread Display D108",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'thread_avgRssi')]) AS \"RSSI (avg)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D108'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'thread_avgRssi')]) AS \"RSSI (avg)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1602333255)\n    AND instance = 'D108'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'thread_latestRssi')]) AS \"RSSI (latest)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D108'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'thread_latestRssi')]) AS \"RSSI (latest)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1602333255)\n    AND instance = 'D108'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'thread_linkQualityIn')]) AS \"Link quality in\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D108'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'thread_linkQualityIn')]) AS \"Link quality in\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1602333255)\n    AND instance = 'D108'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'thread_linkQualityOut')]) AS \"Link quality out\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D108'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'thread_linkQualityOut')]) AS \"Link quality out\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1602333255)\n    AND instance = 'D108'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Thread Display D109",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'thread_avgRssi')]) AS \"RSSI (avg)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D109'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'thread_avgRssi')]) AS \"RSSI (avg)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1611491128)\n    AND instance = 'D109'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'thread_latestRssi')]) AS \"RSSI (latest)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D109'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'thread_latestRssi')]) AS \"RSSI (latest)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1611491128)\n    AND instance = 'D109'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'thread_linkQualityIn')]) AS \"Link quality in\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D109'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'thread_linkQualityIn')]) AS \"Link quality in\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1611491128)\n    AND instance = 'D109'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'thread_linkQualityOut')]) AS \"Link quality out\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D109'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'thread_linkQualityOut')]) AS \"Link quality out\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1611491128)\n    AND instance = 'D109'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Thread Display D110",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'thread_avgRssi')]) AS \"RSSI (avg)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D110'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'thread_avgRssi')]) AS \"RSSI (avg)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1617521070)\n    AND instance = 'D110'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'thread_latestRssi')]) AS \"RSSI (latest)\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D110'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'thread_latestRssi')]) AS \"RSSI (latest)\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1617521070)\n    AND instance = 'D110'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'thread_linkQualityIn')]) AS \"Link quality in\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D110'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'thread_linkQualityIn')]) AS \"Link quality in\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1617521070)\n    AND instance = 'D110'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'thread_linkQualityOut')]) AS \"Link quality out\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D110'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'thread_linkQualityOut')]) AS \"Link quality out\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1617521070)\n    AND instance = 'D110'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  },
  {
   "title": "Lock Voltages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Front door (V500)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensorVoltage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "V500" }
     ]
    },
    {
     "alias": "Storage door (V501)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensorVoltage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "V501" }
     ]
    },
    {
     "alias": "Terrace door (V502)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensorVoltage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "V502" }
     ]
    }
   ]
  },
  {
   "title": "Thread Display Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"D101\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D101'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"D101\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1617521270)\n    AND instance = 'D101'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"D104\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D104'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"D104\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1617521270)\n    AND instance = 'D104'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"D107\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D107'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"D107\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1617521270)\n    AND instance = 'D107'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"D108\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D108'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"D108\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1617521270)\n    AND instance = 'D108'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"D109\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D109'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"D109\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1617521270)\n    AND instance = 'D109'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    },
    {
     "database": "default",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"D110\"\nFROM $table\nWHERE\n    $timeFilter\n    AND instance = 'D110'\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(dt), 60) * 60) * 1000 as t,\n    avg(metric_values[indexOf(metric_names, 'sensorVoltage')]) AS \"D110\"\nFROM default.measurements\nWHERE\n    dt >= toDateTime(1617521270)\n    AND instance = 'D110'\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "measurements"
    }
   ]
  }
 ]
}