{
 "title": "Server summary",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host:",
    "query": {
     "query": "label_values(node_boot_time_seconds, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "host" },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$host.*\"} - node_boot_time_seconds{instance=~\"$host.*\"}"
    }
   ]
  },
  {
   "title": "Load (1m / core)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$host.*\"} / custom_cpu_count"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "custom_cpu_usage{instance=~\"$host.*\",mode=\"user\"}",
     "legendFormat": "user"
    },
    {
     "expr": "custom_cpu_usage{instance=~\"$host.*\",mode=\"system\"}",
     "legendFormat": "system"
    },
    {
     "expr": "custom_cpu_usage{instance=~\"$host.*\",mode=\"iowait\"}",
     "legendFormat": "iowait"
    },
    {
     "expr": "custom_cpu_usage{instance=~\"$host.*\",mode=\"nice\"} + on(instance) custom_cpu_usage{instance=~\"$host.*\",mode=\"irq\"} + on(instance) custom_cpu_usage{instance=~\"$host.*\",mode=\"softirq\"} + on(instance) custom_cpu_usage{instance=~\"$host.*\",mode=\"steal\"}",
     "legendFormat": "other"
    },
    {
     "expr": "custom_cpu_usage{instance=~\"$host.*\",mode=\"idle\"}",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$host.*\"} - node_memory_MemFree_bytes{instance=~\"$host.*\"} - node_memory_Buffers_bytes{instance=~\"$host.*\"} - node_memory_Cached_bytes{instance=~\"$host.*\"} - node_memory_Slab_bytes{instance=~\"$host.*\"} - node_memory_PageTables_bytes{instance=~\"$host.*\"} - node_memory_SwapCached_bytes{instance=~\"$host.*\"}",
     "legendFormat": "Apps"
    },
    {
     "expr": "node_memory_PageTables_bytes{instance=~\"$host.*\"} ",
     "legendFormat": "PageTables"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=~\"$host.*\"}",
     "legendFormat": "SwapCache"
    },
    {
     "expr": "node_memory_Slab_bytes{instance=~\"$host.*\"}",
     "legendFormat": "Slab"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$host.*\"}",
     "legendFormat": "Cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$host.*\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$host.*\"}",
     "legendFormat": "Unused"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$host.*\"} - node_memory_SwapFree_bytes{instance=~\"$host.*\"})",
     "legendFormat": "Swap"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{instance=~\"$host.*\"}",
     "legendFormat": "Corrupted"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~\"$host.*\",fstype!~\"zfs.*\",fstype!~\"fuse.*\",fstype!~\"tmpfs\",mountpoint!=\"/boot\"} - node_filesystem_avail_bytes{instance=~\"$host.*\",fstype!~\"zfs.*\",fstype!~\"fuse.*\",fstype!~\"tmpfs\",mountpoint!=\"/boot\"}) * 100 / node_filesystem_size_bytes{instance=~\"$host.*\",fstype!~\"zfs.*\",fstype!~\"fuse.*\",fstype!~\"tmpfs\",mountpoint!=\"/boot\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "APT Upgrades Pending",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (apt_upgrades_pending{instance=~\"$host.*\"})"
    }
   ]
  }
 ]
}