{
 "title": "Viessmann",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Compressor starts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "heatpump_CompressorStarts{instance=\"viessmann.chacal.fi:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compressor hours",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "heatpump_CompressorHours{instance=\"viessmann.chacal.fi:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pump status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "heatpump_Compressor{instance=\"viessmann.chacal.fi:9100\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "heatpump_DHWHeatingValve{instance=\"viessmann.chacal.fi:9100\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "heatpump_PrimaryPumpSpeed{instance=\"viessmann.chacal.fi:9100\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "heatpump_SecondaryPumpSpeed{instance=\"viessmann.chacal.fi:9100\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "heatpump_CompressorSpeed{instance=\"viessmann.chacal.fi:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Secondary Circuit Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "heatpump_SecondaryCircuitFlowTemp{instance=\"viessmann.chacal.fi:9100\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "heatpump_SecondaryCircuitReturnTemp{instance=\"viessmann.chacal.fi:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Primary Circuit Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "heatpump_PrimaryCircuitFlowTemp{instance=\"viessmann.chacal.fi:9100\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "heatpump_PrimaryCircuitReturnTemp{instance=\"viessmann.chacal.fi:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Warm water temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "heatpump_DHWTopTemp{instance=\"viessmann.chacal.fi:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outdoor temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "heatpump_TempOutdoor{instance=\"viessmann.chacal.fi:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compressor hours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "heatpump_CompressorHours{instance=\"viessmann.chacal.fi:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compressor hours",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(heatpump_CompressorHours{instance=\"viessmann.chacal.fi:9100\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}