---
- name: Install Apt version
  apt:
    state: latest
    pkg: sanoid
  when: ansible_distribution_major_version | int > 10
  tags: sanoid

- name: Install/update sanoid dependencies
  apt:
    state: latest
    cache_valid_time: 3600
    pkg:
      - libcapture-tiny-perl
      - libconfig-inifiles-perl
      - lzop
      - mbuffer
      - perl
      - pv
  when: ansible_distribution_major_version | int < 11
  tags: sanoid


# Sanoid is installed from Sid .deb as it is not available for Buster
- name: Install .deb version
  apt:
    deb: http://deb.debian.org/debian/pool/main/s/sanoid/sanoid_2.0.3-4_all.deb
  when: ansible_distribution_major_version | int < 11
  tags: sanoid
