---
- import_tasks: install.yml

# sanoid .deb also installs systemd timer -> use only that
- name: Disable sanoid cron job
  file:
    path: /etc/cron.d/sanoid
    state: absent
  tags: sanoid

- name: Create systemd override directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/systemd/system/sanoid.service.d
    - /etc/systemd/system/sanoid-prune.service.d
  tags: sanoid

- name: Create systemd override file for sanoid.service
  copy:
    dest: /etc/systemd/system/sanoid.service.d/override.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/sbin/sanoid --take-snapshots
  notify: Reload systemd
  tags: sanoid

- name: Create systemd override file for sanoid-prune.service
  copy:
    dest: /etc/systemd/system/sanoid-prune.service.d/override.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/sbin/sanoid --prune-snapshots
  notify: Reload systemd
  tags: sanoid

- name: Create sanoid config dir
  file:
    path: /etc/sanoid
    state: directory
  tags: sanoid

- name: Configure sanoid
  copy:
    dest: /etc/sanoid/sanoid.conf
    content: "{{ sanoid_config }}"
  tags: sanoid

- name: Clean 0 byte ZFS snapshots to make snapshot handling faster
  cron:
    name: "Clean 0 byte ZFS snapshots"
    job: >
      /usr/sbin/zfs list -t snapshot -o name,used -H
      | grep -v __base__
      | /usr/bin/awk '/autosnap.*\\t0B$/ { print $1 }'
      | xargs -I{} /usr/sbin/zfs destroy {} 2>&1 | /usr/bin/logger -t zfs-snapshot-cleanup
    minute: "{{ sanoid_clean_empty_snapshots_cron_minutes }}"
    hour: "{{ sanoid_clean_empty_snapshots_cron_hours }}"
  when: sanoid_clean_empty_snapshots
  tags: sanoid
