---
- name: Install Ouroboros
  include_role:
    name: docker-app
  vars:
    docker_regular_user: "root"
    docker_app_name: "ouroboros"
    docker_app_container_name: "pyouroboros/ouroboros"
    docker_app_extra_params: "-v /var/run/docker.sock:/var/run/docker.sock"
    docker_app_env:
      - "NOTIFIERS={{ ouroboros_notifier }}"
      - TZ=Europe/Helsinki
      - SELF_UPDATE=true
      - CLEANUP=true
  tags: ouroboros