
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  # For extra security set this to only accept connections on localhost if NGINX is on the same machine
  server_host: 127.0.0.1
  # Update this line to be your domain
  base_url: https://ha.chacal.fi
  use_x_forwarded_for: true
  # You must set the trusted proxy IP address so that Home Assistant will properly accept connections
  # Set this to your NGINX machine IP, or localhost if hosted on the same machine.
  trusted_proxies: 127.0.0.1

recorder:
  purge_keep_days: 180
  db_url: !secret recorder_db_url
  db_max_retries: 30
  db_retry_wait: 10

homeassistant:
  customize_glob:
    binary_sensor.p*:
      device_class: motion

mqtt:
  broker: mqtt-home.chacal.fi
  port: 8883
  client_id: homeassistant
  username: !secret mqtt_username
  password: !secret mqtt_password
  certificate: /etc/ssl/certs/ca-certificates.crt
  tls_version: '1.2'

notify:
  - name: Slack
    platform: slack
    api_key: !secret slack_api_key
    default_channel: '#homeassistant'

switch:
  - platform: rest
    resource: http://esp-433-gateway.chacal.fi/transmit/a/1/1
    name: Guest room table light
    is_on_template: '{{ value_json.state }}'
    body_on: '{"state":true}'
    body_off: '{"state":false}'
    headers:
      Content-Type: application/json
  - platform: rest
    resource: http://esp-433-gateway.chacal.fi/transmit/c/1/1
    name: Stair light
    is_on_template: '{{ value_json.state }}'
    body_on: '{"state":true}'
    body_off: '{"state":false}'
    headers:
      Content-Type: application/json
  - platform: rest
    resource: http://esp-433-gateway.chacal.fi/transmit/a/1/3
    name: Balcony light
    is_on_template: '{{ value_json.state }}'
    body_on: '{"state":true}'
    body_off: '{"state":false}'
    headers:
      Content-Type: application/json
  - platform: rest
    resource: http://esp-433-gateway.chacal.fi/transmit/a/1/2
    name: Front porch light
    is_on_template: '{{ value_json.state }}'
    body_on: '{"state":true}'
    body_off: '{"state":false}'
    headers:
      Content-Type: application/json

light:
  - platform: switch
    name: Stair Christmas Light
    entity_id: switch.stair_light
  - platform: switch
    name: Balcony Christmas Light
    entity_id: switch.balcony_light
  - platform: switch
    name: Front Porch Christmas Light
    entity_id: switch.front_porch_light
  - platform: switch
    name: Guest Room Table Light
    entity_id: switch.guest_room_table_light
  - platform: mount_kelvin
    api_key: !secret houm_api_key

binary_sensor:
  - platform: mqtt
    name: "P300"
    state_topic: '/sensor/P300/k/state'
    value_template: '{{ value_json.motionDetected }}'
    payload_on: true
    payload_off: false
  - platform: mqtt
    name: "P301"
    state_topic: '/sensor/P301/k/state'
    value_template: '{{ value_json.motionDetected }}'
    payload_on: true
    payload_off: false
  - platform: mqtt
    name: "P302"
    state_topic: '/sensor/P302/k/state'
    value_template: '{{ value_json.motionDetected }}'
    payload_on: true
    payload_off: false
  - platform: mqtt
    name: "P303"
    state_topic: '/sensor/P303/k/state'
    value_template: '{{ value_json.motionDetected }}'
    payload_on: true
    payload_off: false
  - platform: mqtt
    name: "P304"
    state_topic: '/sensor/P304/k/state'
    value_template: '{{ value_json.motionDetected }}'
    payload_on: true
    payload_off: false
  - platform: mqtt
    name: "P306"
    state_topic: '/sensor/P306/k/state'
    value_template: '{{ value_json.motionDetected }}'
    payload_on: true
    payload_off: false
  - platform: mqtt
    name: "P307"
    state_topic: '/sensor/P307/k/state'
    value_template: '{{ value_json.motionDetected }}'
    payload_on: true
    payload_off: false
  - platform: mqtt
    name: "P308"
    state_topic: '/sensor/P308/k/state'
    value_template: '{{ value_json.motionDetected }}'
    payload_on: true
    payload_off: false

ios:
