---
- name: Remove Proxmox Enterprise repository
  file: path=/etc/apt/sources.list.d/pve-enterprise.list state=absent

- name: Add Proxmox No-Subscription repository
  apt_repository:
    repo: deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription
    state: present

- name: Create directory for cloud-init userdata files
  file:
    path: /var/lib/vz/snippets
    state: directory

- name: Load required modules for IOMMU
  lineinfile:
    dest: /etc/modules
    state: present
    line: '{{ item }}'
  loop:
    - vfio
    - vfio_iommu_type1
    - vfio_pci
    - vfio_virqfd

- name: Install prometheus node exporter
  import_role:
    name: prometheus_node_exporter

- name: Install prometheus zfs exporter
  import_role:
    name: prometheus_zfs_exporter
