---
- name: Add Elastic apt key
  apt_key: url=https://artifacts.elastic.co/GPG-KEY-elasticsearch state=present
  tags: kibana

- name: Add Elastic apt repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    update_cache: yes
  tags: kibana

- name: Install Kibana
  apt:
    state: latest
    cache_valid_time: 3600
    pkg:
      - kibana
  tags: kibana

- name: Set Kibana config values
  include_tasks: kibana_config_line.yml
  vars:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: server.host, value: "\"{{ ansible_default_ipv4.address }}\"" }
    - { key: server.name, value: "\"{{ inventory_hostname }}\"" }
    - { key: logging.quiet, value: "true" }
    - { key: elasticsearch.hosts, value: "[\"{{ kibana_elasticsearch_url }}\"]" }
    - { key: elasticsearch.username, value: "{{ kibana_elasticsearch_username }}" }
    - { key: elasticsearch.password, value: "{{ kibana_elasticsearch_password }}" }
  tags: kibana

- name: Setup TLS for Kibana UI
  include_tasks: kibana_config_line.yml
  vars:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: server.ssl.certificate, value: "{{ kibana_ssl_cert_path }}" }
    - { key: server.ssl.key, value: "{{ kibana_ssl_key_path }}" }
    - { key: server.ssl.enabled, value: "true" }
  when: kibana_ssl_cert_path != "" and kibana_ssl_key_path != ""
  tags: kibana

- name: Enable and start Kibana
  service: name=kibana state=started enabled=yes
  tags: kibana
