---
- name: Install dependencies
  apt:
    state: latest
    cache_valid_time: 3600
    pkg:
      - smartmontools
      - moreutils
  tags: prometheus_node_exporter

# prometheus-node-exporter is installed from Sid .deb as Buster version has bugs
# See:
# - https://github.com/prometheus/node_exporter/issues/1462
# - https://github.com/prometheus-community/node-exporter-textfile-collector-scripts/pull/8
- name: Install prometheus-node-exporter for x86 Debian
  apt:
    deb: "{{ item }}"
  loop:
    - http://deb.debian.org/debian/pool/main/p/prometheus-node-exporter/prometheus-node-exporter_1.0.1+ds-1_amd64.deb
    - http://deb.debian.org/debian/pool/main/p/prometheus-node-exporter-collectors/prometheus-node-exporter-collectors_0+git20200718.57d05ce-1_all.deb
  when: ansible_lsb.id != "Raspbian"
  tags: prometheus_node_exporter

- name: Install prometheus-node-exporter for Raspbian
  apt:
    deb: "{{ item }}"
  loop:
    - http://archive.raspbian.org/raspbian/pool/main/p/prometheus-node-exporter/prometheus-node-exporter_1.0.1+ds-1_armhf.deb
    - http://archive.raspbian.org/raspbian/pool/main/p/prometheus-node-exporter-collectors/prometheus-node-exporter-collectors_0+git20200718.57d05ce-1_all.deb
  when: ansible_lsb.id == "Raspbian"
  tags: prometheus_node_exporter

- name: Create systemd override directory for prometheus-node-exporter-apt.timer
  file:
    path: /etc/systemd/system/prometheus-node-exporter-apt.timer.d
    state: directory
  tags: prometheus_node_exporter

- name: Create systemd override file for prometheus-node-exporter-apt.timer
  copy:
    dest: /etc/systemd/system/prometheus-node-exporter-apt.timer.d/override.conf
    content: |
      [Unit]
      Description=
      Description=Run apt metrics collection on boot and every 6 hours

      [Timer]
      OnBootSec=0
      OnUnitActiveSec=
      OnCalendar=*-*-* 00/6:00:00
      AccuracySec=5m
  notify:
    - Reload systemd
    - Start apt exporter
  tags: prometheus_node_exporter

- name: Create systemd override directory for /etc/systemd/system/prometheus-node-exporter-smartmon.timer
  file:
    path: /etc/systemd/system/prometheus-node-exporter-smartmon.timer.d
    state: directory
  when: ansible_virtualization_role != "guest"
  tags: prometheus_node_exporter

- name: Create systemd override file for prometheus-node-exporter-smartmon.timer
  copy:
    dest: /etc/systemd/system/prometheus-node-exporter-smartmon.timer.d/override.conf
    content: |
      [Timer]
      OnBootSec=0
      OnUnitActiveSec=
      OnCalendar=*-*-* 00/6:00:00
      AccuracySec=5m
  notify:
    - Reload systemd
    - Start smartmon exporter
  when: ansible_virtualization_role != "guest"
  tags: prometheus_node_exporter

- name: Disable prometheus-node-exporter-smartmon.timer on VMs
  systemd:
    name: prometheus-node-exporter-smartmon.timer
    state: stopped
    enabled: false
    daemon_reload: yes
  when: ansible_virtualization_role == "guest"
  tags: prometheus_node_exporter

- name: Remove existing smartmon run data
  file:
    path: /var/lib/prometheus/node-exporter/smartmon.prom
    state: absent
  when: ansible_virtualization_role == "guest"
  tags: prometheus_node_exporter
