---
- name: Install Debian version
  include_tasks: install_debian_version.yml
  when: ansible_distribution_major_version | int > 10
  tags: prometheus_node_exporter

- name: Install using CloudAlchemy role
  include_tasks: install_using_cloudalchemy.yml
  when: ansible_distribution_major_version | int < 11
  tags: prometheus_node_exporter
