---
- name: Install syncoid
  import_role:
    name: sanoid
    tasks_from: install.yml

- name: Install private key
  copy:
    dest: /root/.ssh/id_rsa_syncoid
    content: "{{ syncoid_private_key }}"
    mode: 0600

- name: Install public key
  authorized_key:
    user: root
    state: present
    key: "{{ syncoid_public_key }}"
  delegate_to: "{{ syncoid_dst_host }}"

- name: Generate excludes list
  set_fact:
    syncoid_excludes_str: "{{ syncoid_excludes | map('regex_replace', '^(.*)$', '--exclude=\\1') | join(' ') }}"

- name: Add syncoid to cron
  cron:
    name: "Syncoid"
    minute: "{{ syncoid_cron_minutes }}"
    hour: "*/2"
    job: "/usr/sbin/syncoid -r --sshkey=/root/.ssh/id_rsa_syncoid {{ syncoid_excludes_str }} {{ syncoid_source }} {{ syncoid_dst_user }}@{{ syncoid_dst_host }}:{{ syncoid_dst_dir }} >> /var/log/syncoid.log 2>&1"
