---
- name: Install syncoid
  import_role:
    name: sanoid
    tasks_from: install.yml
  tags: syncoid

- name: Install private key
  copy:
    dest: /root/.ssh/id_rsa_syncoid
    content: "{{ syncoid_private_key }}"
    mode: 0600
  tags: syncoid

- name: Install public key
  authorized_key:
    user: root
    state: present
    key: "{{ syncoid_public_key }}"
  delegate_to: "{{ syncoid_dst_host }}"
  remote_user: "{{ syncoid_dst_user }}"
  tags: syncoid


- name: Generate excludes list
  set_fact:
    syncoid_excludes_str: "{{ syncoid_excludes | map('regex_replace', '^(.*)$', '--exclude=\\1') | join(' ') }}"
  tags: syncoid

- name: Create systemd service for syncoid
  template:
    src: syncoid.service.j2
    dest: /etc/systemd/system/syncoid.service
  notify: Reload systemd
  tags: syncoid

- name: Create systemd timer for syncoid
  template:
    src: syncoid.timer.j2
    dest: /etc/systemd/system/syncoid.timer
  notify: Reload systemd
  tags: syncoid

- name: Enable and start syncoid timer
  systemd:
    name: syncoid.timer
    daemon_reload: yes
    enabled: yes
    state: started
  tags: syncoid
