---
#
# Playbook that initially sets up signalk-stash.dmz.chacal.fi. Actual SignalK Stash specific installation
# is done using playbooks in signalk-stash repository.
#
- hosts: signalk-stash.dmz.chacal.fi
  remote_user: jihartik
  become: true

  vars_files:
    - secrets.yml

  vars:

  handlers:
    - name: Restart network
      service: name=networking state=restarted

  roles:
    - role: filebeat
      filebeat_elasticsearch_hosts:
        - elastic.chacal.fi
      filebeat_exclude_files:
        - "/var/log/nginx/*"
    - role: debian_common
      unattended_upgrades_origins: '"o=elastic";'
    - role: prometheus_node_exporter
    - role: self_monitoring
    - role: ikifi_with_dma
      tags: ikifi

  tasks:

    - name: Remove default gateway from eth0
      lineinfile:
        dest: /etc/network/interfaces.d/50-cloud-init
        state: absent
        regexp: "gateway"
      notify:
        - Restart network
      tags: network

    - name: Add route to private networks via eth0
      lineinfile:
        dest: /etc/network/interfaces.d/50-cloud-init
        line: "    post-up /usr/sbin/ip route add 10.0.0.0/8 via 10.40.102.1"
        insertafter: 'address'
      notify:
        - Restart network
      tags: network

    - name: Setup WAN interface on ens19
      copy:
        dest: /etc/network/interfaces.d/60-wan.cfg
        content: |
          auto ens19
          iface ens19 inet static
              address 95.217.192.78
              netmask 255.255.255.192
              gateway 95.217.192.65
              dns-nameservers 185.12.64.1 185.12.64.2
      notify:
        - Restart network
      tags: network

