---
- name: Populate service facts
  service_facts:

# Suppress cron default logging
- name: Decrease cron logging
  lineinfile:
    dest: /etc/default/cron
    state: present
    regex: '^EXTRA_OPTS'
    line: 'EXTRA_OPTS="-L 4"'
    insertafter: '^#EXTRA_OPTS'
  notify: Restart cron
  tags: debian_common

- name: Check zed.rc
  stat:
    path: /etc/zfs/zed.d/zed.rc
  register: zed_rc
  tags: debian_common

# By default every Sanoid snapshot creates a logged history event to syslog -> disable that
- name: Disable ZED history_event log spamming
  lineinfile:
    dest: /etc/zfs/zed.d/zed.rc
    state: present
    regex: '^ZED_SYSLOG_SUBCLASS_EXCLUDE'
    line: 'ZED_SYSLOG_SUBCLASS_EXCLUDE="history_event"'
    insertafter: '^#ZED_SYSLOG_SUBCLASS_EXCLUDE'
  when: zed_rc.stat.exists
  tags: debian_common

- name: Disable PAM logging for cron tasks
  lineinfile:
    dest: /etc/pam.d/common-session-noninteractive
    state: present
    regex: '^session [success=1 default=ignore] pam_succeed_if.so service in cron quiet use_uid'
    line: 'session [success=1 default=ignore] pam_succeed_if.so service in cron quiet use_uid'
    insertbefore: '^session.*required.*pam_unix.so'
  tags: debian_common

- name: Install basic tools
  apt:
    state: latest
    cache_valid_time: 3600
    pkg:
      - net-tools
      - sysstat
      - bash-completion
  tags: debian_common

- name: Check rpcbind service
  stat:
    path: /lib/systemd/system/rpcbind.service
  register: rpcbind_service
  tags: debian_common

- name: Stop & disable rpcbind service
  service:
    name: rpcbind
    state: stopped
    enabled: no
  when: rpcbind_service.stat.exists
  tags: debian_common

- name: Stop & disable rpcbind socket
  service:
    name: rpcbind.socket
    state: stopped
    enabled: no
  when: rpcbind_service.stat.exists
  tags: debian_common

- name: Stop & disable smartd on VMs
  service:
    name: smartd
    state: stopped
    enabled: no
  notify: Reset smartd systemd fail state
  when: ansible_virtualization_role == "guest" and ansible_facts.services['smartd.service'] is defined
  tags: debian_common

- name: Run fstrim periodically
  cron:
    name: "Run fstrim"
    minute: "20"
    hour: "*/6"
    job: "/usr/sbin/fstrim -Av 2>&1 | /usr/bin/logger -t fstrim"
  when: ansible_virtualization_role == "guest"
  tags: debian_common

- name: Setup unattended upgrades
  import_role:
    name: unattended_upgrades
  vars:
    unattended_upgrades_email: "{{ chacal.unattended_upgrades.to_email }}"
  tags:
    - debian_common
    - unattended_upgrades
