---
- name: Restart cron
  service:
    name: cron
    state: restarted

- name: Reset smartd systemd fail state
  command: systemctl reset-failed smartd

- name: Restart journald
  service:
    name: systemd-journald.service
    state: restarted
