{
 "title": "ClickHouse",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "clickhouse_node",
    "query": "label_values(host_health, cluster_node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Request duration ($clickhouse_node)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "repeat": "clickhouse_node",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "request_duration_seconds{cluster_node=~\"$clickhouse_node\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Request duration ($clickhouse_node)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "request_duration_seconds{cluster_node=~\"$clickhouse_node\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Success responses / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(status_codes_total{code=\"200\"}[$__interval])",
     "legendFormat": "{{ cluster_node }}"
    }
   ]
  },
  {
   "title": "Error responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "status_codes_total{code!=\"200\"}",
     "legendFormat": "{{ cluster_node }} {{code}}"
    }
   ]
  },
  {
   "title": "Cluster health",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "host_health", "legendFormat": "{{cluster_node}}" }
   ]
  }
 ]
}