{
 "title": "Servers",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host:",
    "query": "label_values(node_boot_time_seconds, instance)"
   },
   {
    "name": "blk_devices",
    "label": "Regex for block devices",
    "query": "label_values(node_disk_read_bytes_total, device)"
   },
   {
    "name": "net_devices",
    "label": "Regex for network devices",
    "query": "label_values(node_network_iface_id, interface)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$host.*\"} - node_boot_time_seconds{instance=~\"$host.*\"}"
    }
   ]
  },
  {
   "title": "CPU System Load (1m / core)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load1{instance=~\"$host.*\"} / custom_cpu_count"
    }
   ]
  },
  {
   "title": "CPU System Load (5m / core)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load5{instance=~\"$host.*\"} / custom_cpu_count"
    }
   ]
  },
  {
   "title": "CPU System Load (15m / core)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load15{instance=~\"$host.*\"} / custom_cpu_count"
    }
   ]
  },
  {
   "title": "APT Upgrades Pending",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (instance) (apt_upgrades_pending{instance=~\"$host.*\"})"
    }
   ]
  },
  {
   "title": "SMART",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "sort(smartmon_device_smart_healthy{instance=~\"$host.*\"})"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "repeat": "host" },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "custom_cpu_usage{instance=~\"$host.*\",mode=\"user\"}",
     "legendFormat": "user"
    },
    {
     "expr": "custom_cpu_usage{instance=~\"$host.*\",mode=\"system\"}",
     "legendFormat": "system"
    },
    {
     "expr": "custom_cpu_usage{instance=~\"$host.*\",mode=\"iowait\"}",
     "legendFormat": "iowait"
    },
    {
     "expr": "custom_cpu_usage{instance=~\"$host.*\",mode=\"nice\"} + on(instance) custom_cpu_usage{instance=~\"$host.*\",mode=\"irq\"} + on(instance) custom_cpu_usage{instance=~\"$host.*\",mode=\"softirq\"} + on(instance) custom_cpu_usage{instance=~\"$host.*\",mode=\"steal\"}",
     "legendFormat": "other"
    },
    {
     "expr": "custom_cpu_usage{instance=~\"$host.*\",mode=\"idle\"}",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "-rate(node_network_receive_bytes_total{instance=~\"$host.*\",device=~\"$net_devices\"}[30s]) * 8",
     "legendFormat": "{{device}} (rx)"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"$host.*\",device=~\"$net_devices\"}[30s]) * 8",
     "legendFormat": "{{device}} (tx)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$host.*\"} - node_memory_MemFree_bytes{instance=~\"$host.*\"} - node_memory_Buffers_bytes{instance=~\"$host.*\"} - node_memory_Cached_bytes{instance=~\"$host.*\"} - node_memory_Slab_bytes{instance=~\"$host.*\"} - node_memory_PageTables_bytes{instance=~\"$host.*\"} - node_memory_SwapCached_bytes{instance=~\"$host.*\"}",
     "legendFormat": "Apps"
    },
    {
     "expr": "node_memory_PageTables_bytes{instance=~\"$host.*\"} ",
     "legendFormat": "PageTables"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=~\"$host.*\"}",
     "legendFormat": "SwapCache"
    },
    {
     "expr": "node_memory_Slab_bytes{instance=~\"$host.*\"}",
     "legendFormat": "Slab"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$host.*\"}",
     "legendFormat": "Cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$host.*\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$host.*\"}",
     "legendFormat": "Unused"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$host.*\"} - node_memory_SwapFree_bytes{instance=~\"$host.*\"})",
     "legendFormat": "Swap"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{instance=~\"$host.*\"}",
     "legendFormat": "Corrupted"
    }
   ]
  },
  {
   "title": "Filesystems",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$host.*\"} - node_filesystem_avail_bytes{instance=~\"$host.*\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$host.*\",device=~\"$blk_devices\"}[1m]) + irate(node_disk_writes_completed_total{instance=~\"$host.*\",device=~\"$blk_devices\"}[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$host.*\",device=~\"$blk_devices\"}[1m])",
     "legendFormat": "{{device}} r"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$host.*\",device=~\"$blk_devices\"}[1m])",
     "legendFormat": "{{device}} w"
    }
   ]
  },
  { "title": "Online status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1054 } },
  {
   "title": "Server online status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1055 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "up", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}