---
- name: Upgrade existing packages
  apt:
    upgrade: dist
    cache_valid_time: 3600

- name: Install base packages
  apt:
    state: latest
    cache_valid_time: 3600
    pkg:
      - net-tools
      - sysstat
      - htop
      - tmux
      - git
      - wget
      - curl
      - less
      - libnss-mdns
      - tcpdump
      - man
      - iftop
      - dnsutils
      - ndisc6
      - avahi-daemon
      - open-vm-tools
      - zsh
      - stow
      - psmisc
      - cloud-init
      - cloud-initramfs-growroot
      - openssh-server
      - bridge-utils